// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: zephyr.proto

package eu.fistar.sdcs.pa;

public final class ZephyrProtos {
  private ZephyrProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ObservationPBOrBuilder extends
      // @@protoc_insertion_point(interface_extends:eu.fistar.ObservationPB)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>required string unit = 2;</code>
     */
    boolean hasUnit();
    /**
     * <code>required string unit = 2;</code>
     */
    java.lang.String getUnit();
    /**
     * <code>required string unit = 2;</code>
     */
    com.google.protobuf.ByteString
        getUnitBytes();

    /**
     * <code>required int64 time = 3;</code>
     */
    boolean hasTime();
    /**
     * <code>required int64 time = 3;</code>
     */
    long getTime();

    /**
     * <code>optional int32 duration = 4;</code>
     */
    boolean hasDuration();
    /**
     * <code>optional int32 duration = 4;</code>
     */
    int getDuration();

    /**
     * <code>repeated string values = 5;</code>
     */
    com.google.protobuf.ProtocolStringList
        getValuesList();
    /**
     * <code>repeated string values = 5;</code>
     */
    int getValuesCount();
    /**
     * <code>repeated string values = 5;</code>
     */
    java.lang.String getValues(int index);
    /**
     * <code>repeated string values = 5;</code>
     */
    com.google.protobuf.ByteString
        getValuesBytes(int index);
  }
  /**
   * Protobuf type {@code eu.fistar.ObservationPB}
   */
  public static final class ObservationPB extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:eu.fistar.ObservationPB)
      ObservationPBOrBuilder {
    // Use ObservationPB.newBuilder() to construct.
    private ObservationPB(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ObservationPB(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ObservationPB defaultInstance;
    public static ObservationPB getDefaultInstance() {
      return defaultInstance;
    }

    public ObservationPB getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ObservationPB(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              name_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              unit_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              time_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              duration_ = input.readInt32();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                values_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000010;
              }
              values_.add(bs);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          values_ = values_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eu.fistar.sdcs.pa.ZephyrProtos.internal_static_eu_fistar_ObservationPB_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eu.fistar.sdcs.pa.ZephyrProtos.internal_static_eu_fistar_ObservationPB_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              eu.fistar.sdcs.pa.ZephyrProtos.ObservationPB.class, eu.fistar.sdcs.pa.ZephyrProtos.ObservationPB.Builder.class);
    }

    public static com.google.protobuf.Parser<ObservationPB> PARSER =
        new com.google.protobuf.AbstractParser<ObservationPB>() {
      public ObservationPB parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ObservationPB(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ObservationPB> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int UNIT_FIELD_NUMBER = 2;
    private java.lang.Object unit_;
    /**
     * <code>required string unit = 2;</code>
     */
    public boolean hasUnit() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string unit = 2;</code>
     */
    public java.lang.String getUnit() {
      java.lang.Object ref = unit_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          unit_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string unit = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUnitBytes() {
      java.lang.Object ref = unit_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        unit_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIME_FIELD_NUMBER = 3;
    private long time_;
    /**
     * <code>required int64 time = 3;</code>
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 time = 3;</code>
     */
    public long getTime() {
      return time_;
    }

    public static final int DURATION_FIELD_NUMBER = 4;
    private int duration_;
    /**
     * <code>optional int32 duration = 4;</code>
     */
    public boolean hasDuration() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 duration = 4;</code>
     */
    public int getDuration() {
      return duration_;
    }

    public static final int VALUES_FIELD_NUMBER = 5;
    private com.google.protobuf.LazyStringList values_;
    /**
     * <code>repeated string values = 5;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getValuesList() {
      return values_;
    }
    /**
     * <code>repeated string values = 5;</code>
     */
    public int getValuesCount() {
      return values_.size();
    }
    /**
     * <code>repeated string values = 5;</code>
     */
    public java.lang.String getValues(int index) {
      return values_.get(index);
    }
    /**
     * <code>repeated string values = 5;</code>
     */
    public com.google.protobuf.ByteString
        getValuesBytes(int index) {
      return values_.getByteString(index);
    }

    private void initFields() {
      name_ = "";
      unit_ = "";
      time_ = 0L;
      duration_ = 0;
      values_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUnit()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getUnitBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, time_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, duration_);
      }
      for (int i = 0; i < values_.size(); i++) {
        output.writeBytes(5, values_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getUnitBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, time_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, duration_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < values_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(values_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getValuesList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static eu.fistar.sdcs.pa.ZephyrProtos.ObservationPB parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static eu.fistar.sdcs.pa.ZephyrProtos.ObservationPB parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static eu.fistar.sdcs.pa.ZephyrProtos.ObservationPB parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static eu.fistar.sdcs.pa.ZephyrProtos.ObservationPB parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static eu.fistar.sdcs.pa.ZephyrProtos.ObservationPB parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static eu.fistar.sdcs.pa.ZephyrProtos.ObservationPB parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static eu.fistar.sdcs.pa.ZephyrProtos.ObservationPB parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static eu.fistar.sdcs.pa.ZephyrProtos.ObservationPB parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static eu.fistar.sdcs.pa.ZephyrProtos.ObservationPB parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static eu.fistar.sdcs.pa.ZephyrProtos.ObservationPB parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(eu.fistar.sdcs.pa.ZephyrProtos.ObservationPB prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code eu.fistar.ObservationPB}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:eu.fistar.ObservationPB)
        eu.fistar.sdcs.pa.ZephyrProtos.ObservationPBOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return eu.fistar.sdcs.pa.ZephyrProtos.internal_static_eu_fistar_ObservationPB_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return eu.fistar.sdcs.pa.ZephyrProtos.internal_static_eu_fistar_ObservationPB_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                eu.fistar.sdcs.pa.ZephyrProtos.ObservationPB.class, eu.fistar.sdcs.pa.ZephyrProtos.ObservationPB.Builder.class);
      }

      // Construct using ZephyrProtos.ObservationPB.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        unit_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        time_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        duration_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        values_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return eu.fistar.sdcs.pa.ZephyrProtos.internal_static_eu_fistar_ObservationPB_descriptor;
      }

      public eu.fistar.sdcs.pa.ZephyrProtos.ObservationPB getDefaultInstanceForType() {
        return eu.fistar.sdcs.pa.ZephyrProtos.ObservationPB.getDefaultInstance();
      }

      public eu.fistar.sdcs.pa.ZephyrProtos.ObservationPB build() {
        eu.fistar.sdcs.pa.ZephyrProtos.ObservationPB result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public eu.fistar.sdcs.pa.ZephyrProtos.ObservationPB buildPartial() {
        eu.fistar.sdcs.pa.ZephyrProtos.ObservationPB result = new eu.fistar.sdcs.pa.ZephyrProtos.ObservationPB(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.unit_ = unit_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.time_ = time_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.duration_ = duration_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          values_ = values_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.values_ = values_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof eu.fistar.sdcs.pa.ZephyrProtos.ObservationPB) {
          return mergeFrom((eu.fistar.sdcs.pa.ZephyrProtos.ObservationPB)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(eu.fistar.sdcs.pa.ZephyrProtos.ObservationPB other) {
        if (other == eu.fistar.sdcs.pa.ZephyrProtos.ObservationPB.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasUnit()) {
          bitField0_ |= 0x00000002;
          unit_ = other.unit_;
          onChanged();
        }
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        if (other.hasDuration()) {
          setDuration(other.getDuration());
        }
        if (!other.values_.isEmpty()) {
          if (values_.isEmpty()) {
            values_ = other.values_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureValuesIsMutable();
            values_.addAll(other.values_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (!hasUnit()) {
          
          return false;
        }
        if (!hasTime()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        eu.fistar.sdcs.pa.ZephyrProtos.ObservationPB parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (eu.fistar.sdcs.pa.ZephyrProtos.ObservationPB) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object unit_ = "";
      /**
       * <code>required string unit = 2;</code>
       */
      public boolean hasUnit() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string unit = 2;</code>
       */
      public java.lang.String getUnit() {
        java.lang.Object ref = unit_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            unit_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string unit = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUnitBytes() {
        java.lang.Object ref = unit_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          unit_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string unit = 2;</code>
       */
      public Builder setUnit(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        unit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string unit = 2;</code>
       */
      public Builder clearUnit() {
        bitField0_ = (bitField0_ & ~0x00000002);
        unit_ = getDefaultInstance().getUnit();
        onChanged();
        return this;
      }
      /**
       * <code>required string unit = 2;</code>
       */
      public Builder setUnitBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        unit_ = value;
        onChanged();
        return this;
      }

      private long time_ ;
      /**
       * <code>required int64 time = 3;</code>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 time = 3;</code>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <code>required int64 time = 3;</code>
       */
      public Builder setTime(long value) {
        bitField0_ |= 0x00000004;
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 time = 3;</code>
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        time_ = 0L;
        onChanged();
        return this;
      }

      private int duration_ ;
      /**
       * <code>optional int32 duration = 4;</code>
       */
      public boolean hasDuration() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 duration = 4;</code>
       */
      public int getDuration() {
        return duration_;
      }
      /**
       * <code>optional int32 duration = 4;</code>
       */
      public Builder setDuration(int value) {
        bitField0_ |= 0x00000008;
        duration_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 duration = 4;</code>
       */
      public Builder clearDuration() {
        bitField0_ = (bitField0_ & ~0x00000008);
        duration_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList values_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureValuesIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          values_ = new com.google.protobuf.LazyStringArrayList(values_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated string values = 5;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getValuesList() {
        return values_.getUnmodifiableView();
      }
      /**
       * <code>repeated string values = 5;</code>
       */
      public int getValuesCount() {
        return values_.size();
      }
      /**
       * <code>repeated string values = 5;</code>
       */
      public java.lang.String getValues(int index) {
        return values_.get(index);
      }
      /**
       * <code>repeated string values = 5;</code>
       */
      public com.google.protobuf.ByteString
          getValuesBytes(int index) {
        return values_.getByteString(index);
      }
      /**
       * <code>repeated string values = 5;</code>
       */
      public Builder setValues(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureValuesIsMutable();
        values_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string values = 5;</code>
       */
      public Builder addValues(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureValuesIsMutable();
        values_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string values = 5;</code>
       */
      public Builder addAllValues(
          java.lang.Iterable<java.lang.String> values) {
        ensureValuesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, values_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string values = 5;</code>
       */
      public Builder clearValues() {
        values_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string values = 5;</code>
       */
      public Builder addValuesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureValuesIsMutable();
        values_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:eu.fistar.ObservationPB)
    }

    static {
      defaultInstance = new ObservationPB(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:eu.fistar.ObservationPB)
  }

  public interface ObservationsPBOrBuilder extends
      // @@protoc_insertion_point(interface_extends:eu.fistar.ObservationsPB)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .eu.fistar.ObservationPB observations = 1;</code>
     */
    java.util.List<eu.fistar.sdcs.pa.ZephyrProtos.ObservationPB> 
        getObservationsList();
    /**
     * <code>repeated .eu.fistar.ObservationPB observations = 1;</code>
     */
    eu.fistar.sdcs.pa.ZephyrProtos.ObservationPB getObservations(int index);
    /**
     * <code>repeated .eu.fistar.ObservationPB observations = 1;</code>
     */
    int getObservationsCount();
    /**
     * <code>repeated .eu.fistar.ObservationPB observations = 1;</code>
     */
    java.util.List<? extends eu.fistar.sdcs.pa.ZephyrProtos.ObservationPBOrBuilder> 
        getObservationsOrBuilderList();
    /**
     * <code>repeated .eu.fistar.ObservationPB observations = 1;</code>
     */
    eu.fistar.sdcs.pa.ZephyrProtos.ObservationPBOrBuilder getObservationsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code eu.fistar.ObservationsPB}
   */
  public static final class ObservationsPB extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:eu.fistar.ObservationsPB)
      ObservationsPBOrBuilder {
    // Use ObservationsPB.newBuilder() to construct.
    private ObservationsPB(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ObservationsPB(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ObservationsPB defaultInstance;
    public static ObservationsPB getDefaultInstance() {
      return defaultInstance;
    }

    public ObservationsPB getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ObservationsPB(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                observations_ = new java.util.ArrayList<eu.fistar.sdcs.pa.ZephyrProtos.ObservationPB>();
                mutable_bitField0_ |= 0x00000001;
              }
              observations_.add(input.readMessage(eu.fistar.sdcs.pa.ZephyrProtos.ObservationPB.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          observations_ = java.util.Collections.unmodifiableList(observations_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eu.fistar.sdcs.pa.ZephyrProtos.internal_static_eu_fistar_ObservationsPB_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eu.fistar.sdcs.pa.ZephyrProtos.internal_static_eu_fistar_ObservationsPB_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              eu.fistar.sdcs.pa.ZephyrProtos.ObservationsPB.class, eu.fistar.sdcs.pa.ZephyrProtos.ObservationsPB.Builder.class);
    }

    public static com.google.protobuf.Parser<ObservationsPB> PARSER =
        new com.google.protobuf.AbstractParser<ObservationsPB>() {
      public ObservationsPB parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ObservationsPB(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ObservationsPB> getParserForType() {
      return PARSER;
    }

    public static final int OBSERVATIONS_FIELD_NUMBER = 1;
    private java.util.List<eu.fistar.sdcs.pa.ZephyrProtos.ObservationPB> observations_;
    /**
     * <code>repeated .eu.fistar.ObservationPB observations = 1;</code>
     */
    public java.util.List<eu.fistar.sdcs.pa.ZephyrProtos.ObservationPB> getObservationsList() {
      return observations_;
    }
    /**
     * <code>repeated .eu.fistar.ObservationPB observations = 1;</code>
     */
    public java.util.List<? extends eu.fistar.sdcs.pa.ZephyrProtos.ObservationPBOrBuilder> 
        getObservationsOrBuilderList() {
      return observations_;
    }
    /**
     * <code>repeated .eu.fistar.ObservationPB observations = 1;</code>
     */
    public int getObservationsCount() {
      return observations_.size();
    }
    /**
     * <code>repeated .eu.fistar.ObservationPB observations = 1;</code>
     */
    public eu.fistar.sdcs.pa.ZephyrProtos.ObservationPB getObservations(int index) {
      return observations_.get(index);
    }
    /**
     * <code>repeated .eu.fistar.ObservationPB observations = 1;</code>
     */
    public eu.fistar.sdcs.pa.ZephyrProtos.ObservationPBOrBuilder getObservationsOrBuilder(
        int index) {
      return observations_.get(index);
    }

    private void initFields() {
      observations_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getObservationsCount(); i++) {
        if (!getObservations(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < observations_.size(); i++) {
        output.writeMessage(1, observations_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < observations_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, observations_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static eu.fistar.sdcs.pa.ZephyrProtos.ObservationsPB parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static eu.fistar.sdcs.pa.ZephyrProtos.ObservationsPB parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static eu.fistar.sdcs.pa.ZephyrProtos.ObservationsPB parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static eu.fistar.sdcs.pa.ZephyrProtos.ObservationsPB parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static eu.fistar.sdcs.pa.ZephyrProtos.ObservationsPB parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static eu.fistar.sdcs.pa.ZephyrProtos.ObservationsPB parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static eu.fistar.sdcs.pa.ZephyrProtos.ObservationsPB parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static eu.fistar.sdcs.pa.ZephyrProtos.ObservationsPB parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static eu.fistar.sdcs.pa.ZephyrProtos.ObservationsPB parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static eu.fistar.sdcs.pa.ZephyrProtos.ObservationsPB parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(eu.fistar.sdcs.pa.ZephyrProtos.ObservationsPB prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code eu.fistar.ObservationsPB}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:eu.fistar.ObservationsPB)
        eu.fistar.sdcs.pa.ZephyrProtos.ObservationsPBOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return eu.fistar.sdcs.pa.ZephyrProtos.internal_static_eu_fistar_ObservationsPB_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return eu.fistar.sdcs.pa.ZephyrProtos.internal_static_eu_fistar_ObservationsPB_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                eu.fistar.sdcs.pa.ZephyrProtos.ObservationsPB.class, eu.fistar.sdcs.pa.ZephyrProtos.ObservationsPB.Builder.class);
      }

      // Construct using ZephyrProtos.ObservationsPB.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getObservationsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (observationsBuilder_ == null) {
          observations_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          observationsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return eu.fistar.sdcs.pa.ZephyrProtos.internal_static_eu_fistar_ObservationsPB_descriptor;
      }

      public eu.fistar.sdcs.pa.ZephyrProtos.ObservationsPB getDefaultInstanceForType() {
        return eu.fistar.sdcs.pa.ZephyrProtos.ObservationsPB.getDefaultInstance();
      }

      public eu.fistar.sdcs.pa.ZephyrProtos.ObservationsPB build() {
        eu.fistar.sdcs.pa.ZephyrProtos.ObservationsPB result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public eu.fistar.sdcs.pa.ZephyrProtos.ObservationsPB buildPartial() {
        eu.fistar.sdcs.pa.ZephyrProtos.ObservationsPB result = new eu.fistar.sdcs.pa.ZephyrProtos.ObservationsPB(this);
        int from_bitField0_ = bitField0_;
        if (observationsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            observations_ = java.util.Collections.unmodifiableList(observations_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.observations_ = observations_;
        } else {
          result.observations_ = observationsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof eu.fistar.sdcs.pa.ZephyrProtos.ObservationsPB) {
          return mergeFrom((eu.fistar.sdcs.pa.ZephyrProtos.ObservationsPB)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(eu.fistar.sdcs.pa.ZephyrProtos.ObservationsPB other) {
        if (other == eu.fistar.sdcs.pa.ZephyrProtos.ObservationsPB.getDefaultInstance()) return this;
        if (observationsBuilder_ == null) {
          if (!other.observations_.isEmpty()) {
            if (observations_.isEmpty()) {
              observations_ = other.observations_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureObservationsIsMutable();
              observations_.addAll(other.observations_);
            }
            onChanged();
          }
        } else {
          if (!other.observations_.isEmpty()) {
            if (observationsBuilder_.isEmpty()) {
              observationsBuilder_.dispose();
              observationsBuilder_ = null;
              observations_ = other.observations_;
              bitField0_ = (bitField0_ & ~0x00000001);
              observationsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getObservationsFieldBuilder() : null;
            } else {
              observationsBuilder_.addAllMessages(other.observations_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getObservationsCount(); i++) {
          if (!getObservations(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        eu.fistar.sdcs.pa.ZephyrProtos.ObservationsPB parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (eu.fistar.sdcs.pa.ZephyrProtos.ObservationsPB) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<eu.fistar.sdcs.pa.ZephyrProtos.ObservationPB> observations_ =
        java.util.Collections.emptyList();
      private void ensureObservationsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          observations_ = new java.util.ArrayList<eu.fistar.sdcs.pa.ZephyrProtos.ObservationPB>(observations_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          eu.fistar.sdcs.pa.ZephyrProtos.ObservationPB, eu.fistar.sdcs.pa.ZephyrProtos.ObservationPB.Builder, eu.fistar.sdcs.pa.ZephyrProtos.ObservationPBOrBuilder> observationsBuilder_;

      /**
       * <code>repeated .eu.fistar.ObservationPB observations = 1;</code>
       */
      public java.util.List<eu.fistar.sdcs.pa.ZephyrProtos.ObservationPB> getObservationsList() {
        if (observationsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(observations_);
        } else {
          return observationsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .eu.fistar.ObservationPB observations = 1;</code>
       */
      public int getObservationsCount() {
        if (observationsBuilder_ == null) {
          return observations_.size();
        } else {
          return observationsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .eu.fistar.ObservationPB observations = 1;</code>
       */
      public eu.fistar.sdcs.pa.ZephyrProtos.ObservationPB getObservations(int index) {
        if (observationsBuilder_ == null) {
          return observations_.get(index);
        } else {
          return observationsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .eu.fistar.ObservationPB observations = 1;</code>
       */
      public Builder setObservations(
          int index, eu.fistar.sdcs.pa.ZephyrProtos.ObservationPB value) {
        if (observationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureObservationsIsMutable();
          observations_.set(index, value);
          onChanged();
        } else {
          observationsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .eu.fistar.ObservationPB observations = 1;</code>
       */
      public Builder setObservations(
          int index, eu.fistar.sdcs.pa.ZephyrProtos.ObservationPB.Builder builderForValue) {
        if (observationsBuilder_ == null) {
          ensureObservationsIsMutable();
          observations_.set(index, builderForValue.build());
          onChanged();
        } else {
          observationsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .eu.fistar.ObservationPB observations = 1;</code>
       */
      public Builder addObservations(eu.fistar.sdcs.pa.ZephyrProtos.ObservationPB value) {
        if (observationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureObservationsIsMutable();
          observations_.add(value);
          onChanged();
        } else {
          observationsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .eu.fistar.ObservationPB observations = 1;</code>
       */
      public Builder addObservations(
          int index, eu.fistar.sdcs.pa.ZephyrProtos.ObservationPB value) {
        if (observationsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureObservationsIsMutable();
          observations_.add(index, value);
          onChanged();
        } else {
          observationsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .eu.fistar.ObservationPB observations = 1;</code>
       */
      public Builder addObservations(
          eu.fistar.sdcs.pa.ZephyrProtos.ObservationPB.Builder builderForValue) {
        if (observationsBuilder_ == null) {
          ensureObservationsIsMutable();
          observations_.add(builderForValue.build());
          onChanged();
        } else {
          observationsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .eu.fistar.ObservationPB observations = 1;</code>
       */
      public Builder addObservations(
          int index, eu.fistar.sdcs.pa.ZephyrProtos.ObservationPB.Builder builderForValue) {
        if (observationsBuilder_ == null) {
          ensureObservationsIsMutable();
          observations_.add(index, builderForValue.build());
          onChanged();
        } else {
          observationsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .eu.fistar.ObservationPB observations = 1;</code>
       */
      public Builder addAllObservations(
          java.lang.Iterable<? extends eu.fistar.sdcs.pa.ZephyrProtos.ObservationPB> values) {
        if (observationsBuilder_ == null) {
          ensureObservationsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, observations_);
          onChanged();
        } else {
          observationsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .eu.fistar.ObservationPB observations = 1;</code>
       */
      public Builder clearObservations() {
        if (observationsBuilder_ == null) {
          observations_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          observationsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .eu.fistar.ObservationPB observations = 1;</code>
       */
      public Builder removeObservations(int index) {
        if (observationsBuilder_ == null) {
          ensureObservationsIsMutable();
          observations_.remove(index);
          onChanged();
        } else {
          observationsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .eu.fistar.ObservationPB observations = 1;</code>
       */
      public eu.fistar.sdcs.pa.ZephyrProtos.ObservationPB.Builder getObservationsBuilder(
          int index) {
        return getObservationsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .eu.fistar.ObservationPB observations = 1;</code>
       */
      public eu.fistar.sdcs.pa.ZephyrProtos.ObservationPBOrBuilder getObservationsOrBuilder(
          int index) {
        if (observationsBuilder_ == null) {
          return observations_.get(index);  } else {
          return observationsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .eu.fistar.ObservationPB observations = 1;</code>
       */
      public java.util.List<? extends eu.fistar.sdcs.pa.ZephyrProtos.ObservationPBOrBuilder> 
           getObservationsOrBuilderList() {
        if (observationsBuilder_ != null) {
          return observationsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(observations_);
        }
      }
      /**
       * <code>repeated .eu.fistar.ObservationPB observations = 1;</code>
       */
      public eu.fistar.sdcs.pa.ZephyrProtos.ObservationPB.Builder addObservationsBuilder() {
        return getObservationsFieldBuilder().addBuilder(
            eu.fistar.sdcs.pa.ZephyrProtos.ObservationPB.getDefaultInstance());
      }
      /**
       * <code>repeated .eu.fistar.ObservationPB observations = 1;</code>
       */
      public eu.fistar.sdcs.pa.ZephyrProtos.ObservationPB.Builder addObservationsBuilder(
          int index) {
        return getObservationsFieldBuilder().addBuilder(
            index, eu.fistar.sdcs.pa.ZephyrProtos.ObservationPB.getDefaultInstance());
      }
      /**
       * <code>repeated .eu.fistar.ObservationPB observations = 1;</code>
       */
      public java.util.List<eu.fistar.sdcs.pa.ZephyrProtos.ObservationPB.Builder> 
           getObservationsBuilderList() {
        return getObservationsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          eu.fistar.sdcs.pa.ZephyrProtos.ObservationPB, eu.fistar.sdcs.pa.ZephyrProtos.ObservationPB.Builder, eu.fistar.sdcs.pa.ZephyrProtos.ObservationPBOrBuilder> 
          getObservationsFieldBuilder() {
        if (observationsBuilder_ == null) {
          observationsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              eu.fistar.sdcs.pa.ZephyrProtos.ObservationPB, eu.fistar.sdcs.pa.ZephyrProtos.ObservationPB.Builder, eu.fistar.sdcs.pa.ZephyrProtos.ObservationPBOrBuilder>(
                  observations_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          observations_ = null;
        }
        return observationsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:eu.fistar.ObservationsPB)
    }

    static {
      defaultInstance = new ObservationsPB(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:eu.fistar.ObservationsPB)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eu_fistar_ObservationPB_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eu_fistar_ObservationPB_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eu_fistar_ObservationsPB_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eu_fistar_ObservationsPB_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014zephyr.proto\022\teu.fistar\"[\n\rObservation" +
      "PB\022\014\n\004name\030\001 \002(\t\022\014\n\004unit\030\002 \002(\t\022\014\n\004time\030\003" +
      " \002(\003\022\020\n\010duration\030\004 \001(\005\022\016\n\006values\030\005 \003(\t\"@" +
      "\n\016ObservationsPB\022.\n\014observations\030\001 \003(\0132\030" +
      ".eu.fistar.ObservationPBB!\n\021eu.fistar.sd" +
      "cs.paB\014ZephyrProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_eu_fistar_ObservationPB_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_eu_fistar_ObservationPB_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_eu_fistar_ObservationPB_descriptor,
        new java.lang.String[] { "Name", "Unit", "Time", "Duration", "Values", });
    internal_static_eu_fistar_ObservationsPB_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_eu_fistar_ObservationsPB_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_eu_fistar_ObservationsPB_descriptor,
        new java.lang.String[] { "Observations", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
