/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.lsl;

public final class ChannelFormatT
{
  public final static ChannelFormatT cf_float32 = new ChannelFormatT("cf_float32", LslAndroidJNI.cf_float32_get());
  public final static ChannelFormatT cf_double64 = new ChannelFormatT("cf_double64", LslAndroidJNI.cf_double64_get());
  public final static ChannelFormatT cf_string = new ChannelFormatT("cf_string", LslAndroidJNI.cf_string_get());
  public final static ChannelFormatT cf_int32 = new ChannelFormatT("cf_int32", LslAndroidJNI.cf_int32_get());
  public final static ChannelFormatT cf_int16 = new ChannelFormatT("cf_int16", LslAndroidJNI.cf_int16_get());
  public final static ChannelFormatT cf_int8 = new ChannelFormatT("cf_int8", LslAndroidJNI.cf_int8_get());
  public final static ChannelFormatT cf_int64 = new ChannelFormatT("cf_int64", LslAndroidJNI.cf_int64_get());
  public final static ChannelFormatT cf_undefined = new ChannelFormatT("cf_undefined", LslAndroidJNI.cf_undefined_get());

  public final int swigValue()
  {
    return swigValue;
  }

  public String toString()
  {
    return swigName;
  }

  public static ChannelFormatT swigToEnum(int swigValue)
  {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
    {
      return swigValues[swigValue];
    }
    for (int i = 0; i < swigValues.length; i++)
    {
      if (swigValues[i].swigValue == swigValue)
      {
        return swigValues[i];
      }
    }
    throw new IllegalArgumentException("No enum " + ChannelFormatT.class + " with value " + swigValue);
  }

  private ChannelFormatT(String swigName)
  {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ChannelFormatT(String swigName, int swigValue)
  {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue + 1;
  }

  private ChannelFormatT(String swigName, ChannelFormatT swigEnum)
  {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue + 1;
  }

  private static ChannelFormatT[] swigValues = {cf_float32, cf_double64, cf_string, cf_int32, cf_int16, cf_int8, cf_int64, cf_undefined};
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

