/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.lsl;

public class ContinuousResolver
{
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ContinuousResolver(long cPtr, boolean cMemoryOwn)
  {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ContinuousResolver obj)
  {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize()
  {
    delete();
  }

  public synchronized void delete()
  {
    if (swigCPtr != 0)
    {
      if (swigCMemOwn)
      {
        swigCMemOwn = false;
        LslAndroidJNI.delete_continuous_resolver(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ContinuousResolver(double forget_after)
  {
    this(LslAndroidJNI.new_continuous_resolver__SWIG_0(forget_after), true);
  }

  public ContinuousResolver()
  {
    this(LslAndroidJNI.new_continuous_resolver__SWIG_1(), true);
  }

  public ContinuousResolver(String prop, String value, double forget_after)
  {
    this(LslAndroidJNI.new_continuous_resolver__SWIG_2(prop, value, forget_after), true);
  }

  public ContinuousResolver(String prop, String value)
  {
    this(LslAndroidJNI.new_continuous_resolver__SWIG_3(prop, value), true);
  }

  public ContinuousResolver(String pred, double forget_after)
  {
    this(LslAndroidJNI.new_continuous_resolver__SWIG_4(pred, forget_after), true);
  }

  public ContinuousResolver(String pred)
  {
    this(LslAndroidJNI.new_continuous_resolver__SWIG_5(pred), true);
  }

  public VectorInfo results()
  {
    return new VectorInfo(LslAndroidJNI.continuous_resolver_results(swigCPtr, this), true);
  }
}
