/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.lsl;

public class LslAndroidJNI
{
  public static native double IRREGULAR_RATE_get();

  public static native double DEDUCED_TIMESTAMP_get();

  public static native double FOREVER_get();

  public static native int cf_float32_get();

  public static native int cf_double64_get();

  public static native int cf_string_get();

  public static native int cf_int32_get();

  public static native int cf_int16_get();

  public static native int cf_int8_get();

  public static native int cf_int64_get();

  public static native int cf_undefined_get();

  public static native int protocol_version();

  public static native int library_version();

  public static native double local_clock();

  public static native long new_stream_info__SWIG_0(String jarg1, String jarg2, int jarg3, double jarg4, int jarg5, String jarg6);

  public static native long new_stream_info__SWIG_1(String jarg1, String jarg2, int jarg3, double jarg4, int jarg5);

  public static native long new_stream_info__SWIG_2(String jarg1, String jarg2, int jarg3, double jarg4);

  public static native long new_stream_info__SWIG_3(String jarg1, String jarg2, int jarg3);

  public static native long new_stream_info__SWIG_4(String jarg1, String jarg2);

  public static native long new_stream_info__SWIG_5(long jarg1);

  public static native String stream_info_name(long jarg1, StreamInfo jarg1_);

  public static native String stream_info_type(long jarg1, StreamInfo jarg1_);

  public static native int stream_info_channel_count(long jarg1, StreamInfo jarg1_);

  public static native double stream_info_nominal_srate(long jarg1, StreamInfo jarg1_);

  public static native int stream_info_channel_format(long jarg1, StreamInfo jarg1_);

  public static native String stream_info_source_id(long jarg1, StreamInfo jarg1_);

  public static native int stream_info_version(long jarg1, StreamInfo jarg1_);

  public static native double stream_info_created_at(long jarg1, StreamInfo jarg1_);

  public static native String stream_info_uid(long jarg1, StreamInfo jarg1_);

  public static native String stream_info_session_id(long jarg1, StreamInfo jarg1_);

  public static native String stream_info_hostname(long jarg1, StreamInfo jarg1_);

  public static native long stream_info_desc(long jarg1, StreamInfo jarg1_);

  public static native String stream_info_as_xml(long jarg1, StreamInfo jarg1_);

  public static native int stream_info_channel_bytes(long jarg1, StreamInfo jarg1_);

  public static native int stream_info_sample_bytes(long jarg1, StreamInfo jarg1_);

  public static native long stream_info_handle(long jarg1, StreamInfo jarg1_);

  public static native long new_stream_info__SWIG_6();

  public static native long new_stream_info__SWIG_7(long jarg1, StreamInfo jarg1_);

  public static native void delete_stream_info(long jarg1);

  public static native long stream_info_from_xml(String jarg1);

  public static native long new_stream_outlet__SWIG_0(long jarg1, StreamInfo jarg1_, int jarg2, int jarg3);

  public static native long new_stream_outlet__SWIG_1(long jarg1, StreamInfo jarg1_, int jarg2);

  public static native long new_stream_outlet__SWIG_2(long jarg1, StreamInfo jarg1_);

  public static native void stream_outlet_push_sample__SWIG_3(long jarg1, StreamOutlet jarg1_, long jarg2, VectorF jarg2_, double jarg3, boolean jarg4);

  public static native void stream_outlet_push_sample__SWIG_4(long jarg1, StreamOutlet jarg1_, long jarg2, VectorF jarg2_, double jarg3);

  public static native void stream_outlet_push_sample__SWIG_5(long jarg1, StreamOutlet jarg1_, long jarg2, VectorF jarg2_);

  public static native void stream_outlet_push_sample__SWIG_6(long jarg1, StreamOutlet jarg1_, long jarg2, VectorD jarg2_, double jarg3, boolean jarg4);

  public static native void stream_outlet_push_sample__SWIG_7(long jarg1, StreamOutlet jarg1_, long jarg2, VectorD jarg2_, double jarg3);

  public static native void stream_outlet_push_sample__SWIG_8(long jarg1, StreamOutlet jarg1_, long jarg2, VectorD jarg2_);

  public static native void stream_outlet_push_sample__SWIG_9(long jarg1, StreamOutlet jarg1_, long jarg2, VectorL jarg2_, double jarg3, boolean jarg4);

  public static native void stream_outlet_push_sample__SWIG_10(long jarg1, StreamOutlet jarg1_, long jarg2, VectorL jarg2_, double jarg3);

  public static native void stream_outlet_push_sample__SWIG_11(long jarg1, StreamOutlet jarg1_, long jarg2, VectorL jarg2_);

  public static native void stream_outlet_push_sample__SWIG_12(long jarg1, StreamOutlet jarg1_, long jarg2, VectorI jarg2_, double jarg3, boolean jarg4);

  public static native void stream_outlet_push_sample__SWIG_13(long jarg1, StreamOutlet jarg1_, long jarg2, VectorI jarg2_, double jarg3);

  public static native void stream_outlet_push_sample__SWIG_14(long jarg1, StreamOutlet jarg1_, long jarg2, VectorI jarg2_);

  public static native void stream_outlet_push_sample__SWIG_15(long jarg1, StreamOutlet jarg1_, long jarg2, VectorS jarg2_, double jarg3, boolean jarg4);

  public static native void stream_outlet_push_sample__SWIG_16(long jarg1, StreamOutlet jarg1_, long jarg2, VectorS jarg2_, double jarg3);

  public static native void stream_outlet_push_sample__SWIG_17(long jarg1, StreamOutlet jarg1_, long jarg2, VectorS jarg2_);

  public static native void stream_outlet_push_sample__SWIG_18(long jarg1, StreamOutlet jarg1_, long jarg2, double jarg3, boolean jarg4);

  public static native void stream_outlet_push_sample__SWIG_19(long jarg1, StreamOutlet jarg1_, long jarg2, double jarg3);

  public static native void stream_outlet_push_sample__SWIG_20(long jarg1, StreamOutlet jarg1_, long jarg2);

  public static native void stream_outlet_push_sample__SWIG_21(long jarg1, StreamOutlet jarg1_, long jarg2, VectorStr jarg2_, double jarg3, boolean jarg4);

  public static native void stream_outlet_push_sample__SWIG_22(long jarg1, StreamOutlet jarg1_, long jarg2, VectorStr jarg2_, double jarg3);

  public static native void stream_outlet_push_sample__SWIG_23(long jarg1, StreamOutlet jarg1_, long jarg2, VectorStr jarg2_);

  public static native void stream_outlet_push_sample__SWIG_24(long jarg1, StreamOutlet jarg1_, long jarg2, double jarg3, boolean jarg4);

  public static native void stream_outlet_push_sample__SWIG_25(long jarg1, StreamOutlet jarg1_, long jarg2, double jarg3);

  public static native void stream_outlet_push_sample__SWIG_26(long jarg1, StreamOutlet jarg1_, long jarg2);

  public static native void stream_outlet_push_sample__SWIG_27(long jarg1, StreamOutlet jarg1_, long jarg2, double jarg3, boolean jarg4);

  public static native void stream_outlet_push_sample__SWIG_28(long jarg1, StreamOutlet jarg1_, long jarg2, double jarg3);

  public static native void stream_outlet_push_sample__SWIG_29(long jarg1, StreamOutlet jarg1_, long jarg2);

  public static native void stream_outlet_push_sample__SWIG_30(long jarg1, StreamOutlet jarg1_, long jarg2, double jarg3, boolean jarg4);

  public static native void stream_outlet_push_sample__SWIG_31(long jarg1, StreamOutlet jarg1_, long jarg2, double jarg3);

  public static native void stream_outlet_push_sample__SWIG_32(long jarg1, StreamOutlet jarg1_, long jarg2);

  public static native void stream_outlet_push_sample__SWIG_33(long jarg1, StreamOutlet jarg1_, long jarg2, double jarg3, boolean jarg4);

  public static native void stream_outlet_push_sample__SWIG_34(long jarg1, StreamOutlet jarg1_, long jarg2, double jarg3);

  public static native void stream_outlet_push_sample__SWIG_35(long jarg1, StreamOutlet jarg1_, long jarg2);

  public static native void stream_outlet_push_sample__SWIG_36(long jarg1, StreamOutlet jarg1_, long jarg2, double jarg3, boolean jarg4);

  public static native void stream_outlet_push_sample__SWIG_37(long jarg1, StreamOutlet jarg1_, long jarg2, double jarg3);

  public static native void stream_outlet_push_sample__SWIG_38(long jarg1, StreamOutlet jarg1_, long jarg2);

  public static native void stream_outlet_push_sample__SWIG_39(long jarg1, StreamOutlet jarg1_, String jarg2, double jarg3, boolean jarg4);

  public static native void stream_outlet_push_sample__SWIG_40(long jarg1, StreamOutlet jarg1_, String jarg2, double jarg3);

  public static native void stream_outlet_push_sample__SWIG_41(long jarg1, StreamOutlet jarg1_, String jarg2);

  public static native void stream_outlet_push_sample__SWIG_42(long jarg1, StreamOutlet jarg1_, long jarg2, double jarg3, boolean jarg4);

  public static native void stream_outlet_push_sample__SWIG_43(long jarg1, StreamOutlet jarg1_, long jarg2, double jarg3);

  public static native void stream_outlet_push_sample__SWIG_44(long jarg1, StreamOutlet jarg1_, long jarg2);

  public static native void stream_outlet_push_numeric_raw__SWIG_0(long jarg1, StreamOutlet jarg1_, long jarg2, double jarg3, boolean jarg4);

  public static native void stream_outlet_push_numeric_raw__SWIG_1(long jarg1, StreamOutlet jarg1_, long jarg2, double jarg3);

  public static native void stream_outlet_push_numeric_raw__SWIG_2(long jarg1, StreamOutlet jarg1_, long jarg2);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_0(long jarg1, StreamOutlet jarg1_, long jarg2, VectorF jarg2_, double jarg3, boolean jarg4);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_1(long jarg1, StreamOutlet jarg1_, long jarg2, VectorF jarg2_, double jarg3);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_2(long jarg1, StreamOutlet jarg1_, long jarg2, VectorF jarg2_);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_3(long jarg1, StreamOutlet jarg1_, long jarg2, VectorD jarg2_, double jarg3, boolean jarg4);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_4(long jarg1, StreamOutlet jarg1_, long jarg2, VectorD jarg2_, double jarg3);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_5(long jarg1, StreamOutlet jarg1_, long jarg2, VectorD jarg2_);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_6(long jarg1, StreamOutlet jarg1_, long jarg2, VectorL jarg2_, double jarg3, boolean jarg4);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_7(long jarg1, StreamOutlet jarg1_, long jarg2, VectorL jarg2_, double jarg3);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_8(long jarg1, StreamOutlet jarg1_, long jarg2, VectorL jarg2_);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_9(long jarg1, StreamOutlet jarg1_, long jarg2, VectorI jarg2_, double jarg3, boolean jarg4);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_10(long jarg1, StreamOutlet jarg1_, long jarg2, VectorI jarg2_, double jarg3);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_11(long jarg1, StreamOutlet jarg1_, long jarg2, VectorI jarg2_);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_12(long jarg1, StreamOutlet jarg1_, long jarg2, VectorS jarg2_, double jarg3, boolean jarg4);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_13(long jarg1, StreamOutlet jarg1_, long jarg2, VectorS jarg2_, double jarg3);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_14(long jarg1, StreamOutlet jarg1_, long jarg2, VectorS jarg2_);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_15(long jarg1, StreamOutlet jarg1_, long jarg2, double jarg3, boolean jarg4);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_16(long jarg1, StreamOutlet jarg1_, long jarg2, double jarg3);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_17(long jarg1, StreamOutlet jarg1_, long jarg2);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_18(long jarg1, StreamOutlet jarg1_, long jarg2, VectorStr jarg2_, double jarg3, boolean jarg4);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_19(long jarg1, StreamOutlet jarg1_, long jarg2, VectorStr jarg2_, double jarg3);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_20(long jarg1, StreamOutlet jarg1_, long jarg2, VectorStr jarg2_);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_21(long jarg1, StreamOutlet jarg1_, long jarg2, VectorF jarg2_, long jarg3, VectorD jarg3_, boolean jarg4);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_22(long jarg1, StreamOutlet jarg1_, long jarg2, VectorF jarg2_, long jarg3, VectorD jarg3_);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_23(long jarg1, StreamOutlet jarg1_, long jarg2, VectorD jarg2_, long jarg3, VectorD jarg3_, boolean jarg4);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_24(long jarg1, StreamOutlet jarg1_, long jarg2, VectorD jarg2_, long jarg3, VectorD jarg3_);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_25(long jarg1, StreamOutlet jarg1_, long jarg2, VectorL jarg2_, long jarg3, VectorD jarg3_, boolean jarg4);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_26(long jarg1, StreamOutlet jarg1_, long jarg2, VectorL jarg2_, long jarg3, VectorD jarg3_);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_27(long jarg1, StreamOutlet jarg1_, long jarg2, VectorI jarg2_, long jarg3, VectorD jarg3_, boolean jarg4);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_28(long jarg1, StreamOutlet jarg1_, long jarg2, VectorI jarg2_, long jarg3, VectorD jarg3_);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_29(long jarg1, StreamOutlet jarg1_, long jarg2, VectorS jarg2_, long jarg3, VectorD jarg3_, boolean jarg4);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_30(long jarg1, StreamOutlet jarg1_, long jarg2, VectorS jarg2_, long jarg3, VectorD jarg3_);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_31(long jarg1, StreamOutlet jarg1_, long jarg2, long jarg3, VectorD jarg3_, boolean jarg4);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_32(long jarg1, StreamOutlet jarg1_, long jarg2, long jarg3, VectorD jarg3_);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_33(
      long jarg1, StreamOutlet jarg1_, long jarg2, VectorStr jarg2_, long jarg3, VectorD jarg3_, boolean jarg4);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_34(long jarg1, StreamOutlet jarg1_, long jarg2, VectorStr jarg2_, long jarg3, VectorD jarg3_);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_35(long jarg1, StreamOutlet jarg1_, long jarg2, long jarg3, double jarg4, boolean jarg5);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_36(long jarg1, StreamOutlet jarg1_, long jarg2, long jarg3, double jarg4);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_37(long jarg1, StreamOutlet jarg1_, long jarg2, long jarg3);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_38(long jarg1, StreamOutlet jarg1_, long jarg2, long jarg3, double jarg4, boolean jarg5);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_39(long jarg1, StreamOutlet jarg1_, long jarg2, long jarg3, double jarg4);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_40(long jarg1, StreamOutlet jarg1_, long jarg2, long jarg3);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_41(long jarg1, StreamOutlet jarg1_, long jarg2, long jarg3, double jarg4, boolean jarg5);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_42(long jarg1, StreamOutlet jarg1_, long jarg2, long jarg3, double jarg4);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_43(long jarg1, StreamOutlet jarg1_, long jarg2, long jarg3);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_44(long jarg1, StreamOutlet jarg1_, long jarg2, long jarg3, double jarg4, boolean jarg5);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_45(long jarg1, StreamOutlet jarg1_, long jarg2, long jarg3, double jarg4);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_46(long jarg1, StreamOutlet jarg1_, long jarg2, long jarg3);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_47(long jarg1, StreamOutlet jarg1_, long jarg2, long jarg3, double jarg4, boolean jarg5);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_48(long jarg1, StreamOutlet jarg1_, long jarg2, long jarg3, double jarg4);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_49(long jarg1, StreamOutlet jarg1_, long jarg2, long jarg3);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_50(long jarg1, StreamOutlet jarg1_, String jarg2, long jarg3, double jarg4, boolean jarg5);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_51(long jarg1, StreamOutlet jarg1_, String jarg2, long jarg3, double jarg4);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_52(long jarg1, StreamOutlet jarg1_, String jarg2, long jarg3);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_53(long jarg1, StreamOutlet jarg1_, long jarg2, long jarg3, double jarg4, boolean jarg5);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_54(long jarg1, StreamOutlet jarg1_, long jarg2, long jarg3, double jarg4);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_55(long jarg1, StreamOutlet jarg1_, long jarg2, long jarg3);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_56(long jarg1, StreamOutlet jarg1_, long jarg2, long jarg3, long jarg4, boolean jarg5);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_57(long jarg1, StreamOutlet jarg1_, long jarg2, long jarg3, long jarg4);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_58(long jarg1, StreamOutlet jarg1_, long jarg2, long jarg3, long jarg4, boolean jarg5);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_59(long jarg1, StreamOutlet jarg1_, long jarg2, long jarg3, long jarg4);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_60(long jarg1, StreamOutlet jarg1_, long jarg2, long jarg3, long jarg4, boolean jarg5);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_61(long jarg1, StreamOutlet jarg1_, long jarg2, long jarg3, long jarg4);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_62(long jarg1, StreamOutlet jarg1_, long jarg2, long jarg3, long jarg4, boolean jarg5);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_63(long jarg1, StreamOutlet jarg1_, long jarg2, long jarg3, long jarg4);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_64(long jarg1, StreamOutlet jarg1_, long jarg2, long jarg3, long jarg4, boolean jarg5);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_65(long jarg1, StreamOutlet jarg1_, long jarg2, long jarg3, long jarg4);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_66(long jarg1, StreamOutlet jarg1_, String jarg2, long jarg3, long jarg4, boolean jarg5);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_67(long jarg1, StreamOutlet jarg1_, String jarg2, long jarg3, long jarg4);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_68(long jarg1, StreamOutlet jarg1_, long jarg2, long jarg3, long jarg4, boolean jarg5);

  public static native void stream_outlet_push_chunk_multiplexed__SWIG_69(long jarg1, StreamOutlet jarg1_, long jarg2, long jarg3, long jarg4);

  public static native boolean stream_outlet_have_consumers(long jarg1, StreamOutlet jarg1_);

  public static native boolean stream_outlet_wait_for_consumers(long jarg1, StreamOutlet jarg1_, double jarg2);

  public static native long stream_outlet_info(long jarg1, StreamOutlet jarg1_);

  public static native void delete_stream_outlet(long jarg1);

  public static native long resolve_streams__SWIG_0(double jarg1);

  public static native long resolve_streams__SWIG_1();

  public static native long resolve_stream__SWIG_0(String jarg1, String jarg2, int jarg3, double jarg4);

  public static native long resolve_stream__SWIG_1(String jarg1, String jarg2, int jarg3);

  public static native long resolve_stream__SWIG_2(String jarg1, String jarg2);

  public static native long resolve_stream__SWIG_3(String jarg1, int jarg2, double jarg3);

  public static native long resolve_stream__SWIG_4(String jarg1, int jarg2);

  public static native long resolve_stream__SWIG_5(String jarg1);

  public static native void check_error(int jarg1);

  public static native long new_stream_inlet__SWIG_0(long jarg1, StreamInfo jarg1_, int jarg2, int jarg3, boolean jarg4);

  public static native long new_stream_inlet__SWIG_1(long jarg1, StreamInfo jarg1_, int jarg2, int jarg3);

  public static native long new_stream_inlet__SWIG_2(long jarg1, StreamInfo jarg1_, int jarg2);

  public static native long new_stream_inlet__SWIG_3(long jarg1, StreamInfo jarg1_);

  public static native void delete_stream_inlet(long jarg1);

  public static native long stream_inlet_info__SWIG_0(long jarg1, StreamInlet jarg1_, double jarg2);

  public static native long stream_inlet_info__SWIG_1(long jarg1, StreamInlet jarg1_);

  public static native void stream_inlet_open_stream__SWIG_0(long jarg1, StreamInlet jarg1_, double jarg2);

  public static native void stream_inlet_open_stream__SWIG_1(long jarg1, StreamInlet jarg1_);

  public static native void stream_inlet_close_stream(long jarg1, StreamInlet jarg1_);

  public static native double stream_inlet_time_correction__SWIG_0(long jarg1, StreamInlet jarg1_, double jarg2);

  public static native double stream_inlet_time_correction__SWIG_1(long jarg1, StreamInlet jarg1_);

  public static native double stream_inlet_pull_sample__SWIG_2(long jarg1, StreamInlet jarg1_, long jarg2, VectorF jarg2_, double jarg3);

  public static native double stream_inlet_pull_sample__SWIG_3(long jarg1, StreamInlet jarg1_, long jarg2, VectorF jarg2_);

  public static native double stream_inlet_pull_sample__SWIG_4(long jarg1, StreamInlet jarg1_, long jarg2, VectorD jarg2_, double jarg3);

  public static native double stream_inlet_pull_sample__SWIG_5(long jarg1, StreamInlet jarg1_, long jarg2, VectorD jarg2_);

  public static native double stream_inlet_pull_sample__SWIG_6(long jarg1, StreamInlet jarg1_, long jarg2, VectorL jarg2_, double jarg3);

  public static native double stream_inlet_pull_sample__SWIG_7(long jarg1, StreamInlet jarg1_, long jarg2, VectorL jarg2_);

  public static native double stream_inlet_pull_sample__SWIG_8(long jarg1, StreamInlet jarg1_, long jarg2, VectorI jarg2_, double jarg3);

  public static native double stream_inlet_pull_sample__SWIG_9(long jarg1, StreamInlet jarg1_, long jarg2, VectorI jarg2_);

  public static native double stream_inlet_pull_sample__SWIG_10(long jarg1, StreamInlet jarg1_, long jarg2, VectorS jarg2_, double jarg3);

  public static native double stream_inlet_pull_sample__SWIG_11(long jarg1, StreamInlet jarg1_, long jarg2, VectorS jarg2_);

  public static native double stream_inlet_pull_sample__SWIG_12(long jarg1, StreamInlet jarg1_, long jarg2, double jarg3);

  public static native double stream_inlet_pull_sample__SWIG_13(long jarg1, StreamInlet jarg1_, long jarg2);

  public static native double stream_inlet_pull_sample__SWIG_14(long jarg1, StreamInlet jarg1_, long jarg2, VectorStr jarg2_, double jarg3);

  public static native double stream_inlet_pull_sample__SWIG_15(long jarg1, StreamInlet jarg1_, long jarg2, VectorStr jarg2_);

  public static native double stream_inlet_pull_sample__SWIG_16(long jarg1, StreamInlet jarg1_, long jarg2, int jarg3, double jarg4);

  public static native double stream_inlet_pull_sample__SWIG_17(long jarg1, StreamInlet jarg1_, long jarg2, int jarg3);

  public static native double stream_inlet_pull_sample__SWIG_18(long jarg1, StreamInlet jarg1_, long jarg2, int jarg3, double jarg4);

  public static native double stream_inlet_pull_sample__SWIG_19(long jarg1, StreamInlet jarg1_, long jarg2, int jarg3);

  public static native double stream_inlet_pull_sample__SWIG_20(long jarg1, StreamInlet jarg1_, long jarg2, int jarg3, double jarg4);

  public static native double stream_inlet_pull_sample__SWIG_21(long jarg1, StreamInlet jarg1_, long jarg2, int jarg3);

  public static native double stream_inlet_pull_sample__SWIG_22(long jarg1, StreamInlet jarg1_, long jarg2, int jarg3, double jarg4);

  public static native double stream_inlet_pull_sample__SWIG_23(long jarg1, StreamInlet jarg1_, long jarg2, int jarg3);

  public static native double stream_inlet_pull_sample__SWIG_24(long jarg1, StreamInlet jarg1_, long jarg2, int jarg3, double jarg4);

  public static native double stream_inlet_pull_sample__SWIG_25(long jarg1, StreamInlet jarg1_, long jarg2, int jarg3);

  public static native double stream_inlet_pull_sample__SWIG_26(long jarg1, StreamInlet jarg1_, String jarg2, int jarg3, double jarg4);

  public static native double stream_inlet_pull_sample__SWIG_27(long jarg1, StreamInlet jarg1_, String jarg2, int jarg3);

  public static native double stream_inlet_pull_sample__SWIG_28(long jarg1, StreamInlet jarg1_, long jarg2, int jarg3, double jarg4);

  public static native double stream_inlet_pull_sample__SWIG_29(long jarg1, StreamInlet jarg1_, long jarg2, int jarg3);

  public static native double stream_inlet_pull_numeric_raw__SWIG_0(long jarg1, StreamInlet jarg1_, long jarg2, int jarg3, double jarg4);

  public static native double stream_inlet_pull_numeric_raw__SWIG_1(long jarg1, StreamInlet jarg1_, long jarg2, int jarg3);

  public static native long stream_inlet_pull_chunk_multiplexed__SWIG_0(long jarg1, StreamInlet jarg1_, long jarg2, long jarg3, long jarg4, long jarg5, double jarg6);

  public static native long stream_inlet_pull_chunk_multiplexed__SWIG_1(long jarg1, StreamInlet jarg1_, long jarg2, long jarg3, long jarg4, long jarg5);

  public static native long stream_inlet_pull_chunk_multiplexed__SWIG_2(long jarg1, StreamInlet jarg1_, long jarg2, long jarg3, long jarg4, long jarg5, double jarg6);

  public static native long stream_inlet_pull_chunk_multiplexed__SWIG_3(long jarg1, StreamInlet jarg1_, long jarg2, long jarg3, long jarg4, long jarg5);

  public static native long stream_inlet_pull_chunk_multiplexed__SWIG_4(long jarg1, StreamInlet jarg1_, long jarg2, long jarg3, long jarg4, long jarg5, double jarg6);

  public static native long stream_inlet_pull_chunk_multiplexed__SWIG_5(long jarg1, StreamInlet jarg1_, long jarg2, long jarg3, long jarg4, long jarg5);

  public static native long stream_inlet_pull_chunk_multiplexed__SWIG_6(long jarg1, StreamInlet jarg1_, long jarg2, long jarg3, long jarg4, long jarg5, double jarg6);

  public static native long stream_inlet_pull_chunk_multiplexed__SWIG_7(long jarg1, StreamInlet jarg1_, long jarg2, long jarg3, long jarg4, long jarg5);

  public static native long stream_inlet_pull_chunk_multiplexed__SWIG_8(long jarg1, StreamInlet jarg1_, long jarg2, long jarg3, long jarg4, long jarg5, double jarg6);

  public static native long stream_inlet_pull_chunk_multiplexed__SWIG_9(long jarg1, StreamInlet jarg1_, long jarg2, long jarg3, long jarg4, long jarg5);

  public static native long stream_inlet_pull_chunk_multiplexed__SWIG_10(long jarg1, StreamInlet jarg1_, String jarg2, long jarg3, long jarg4, long jarg5, double jarg6);

  public static native long stream_inlet_pull_chunk_multiplexed__SWIG_11(long jarg1, StreamInlet jarg1_, String jarg2, long jarg3, long jarg4, long jarg5);

  public static native long stream_inlet_pull_chunk_multiplexed__SWIG_12(long jarg1, StreamInlet jarg1_, long jarg2, long jarg3, long jarg4, long jarg5, double jarg6);

  public static native long stream_inlet_pull_chunk_multiplexed__SWIG_13(long jarg1, StreamInlet jarg1_, long jarg2, long jarg3, long jarg4, long jarg5);

  public static native long stream_inlet_samples_available(long jarg1, StreamInlet jarg1_);

  public static native boolean stream_inlet_was_clock_reset(long jarg1, StreamInlet jarg1_);

  public static native long new_xml_element(long jarg1);

  public static native long xml_element_first_child(long jarg1, XmlElement jarg1_);

  public static native long xml_element_last_child(long jarg1, XmlElement jarg1_);

  public static native long xml_element_next_sibling__SWIG_0(long jarg1, XmlElement jarg1_);

  public static native long xml_element_previous_sibling__SWIG_0(long jarg1, XmlElement jarg1_);

  public static native long xml_element_parent(long jarg1, XmlElement jarg1_);

  public static native long xml_element_child(long jarg1, XmlElement jarg1_, String jarg2);

  public static native long xml_element_next_sibling__SWIG_1(long jarg1, XmlElement jarg1_, String jarg2);

  public static native long xml_element_previous_sibling__SWIG_1(long jarg1, XmlElement jarg1_, String jarg2);

  public static native boolean xml_element_empty(long jarg1, XmlElement jarg1_);

  public static native boolean xml_element_is_text(long jarg1, XmlElement jarg1_);

  public static native String xml_element_name(long jarg1, XmlElement jarg1_);

  public static native String xml_element_value(long jarg1, XmlElement jarg1_);

  public static native String xml_element_child_value__SWIG_0(long jarg1, XmlElement jarg1_);

  public static native String xml_element_child_value__SWIG_1(long jarg1, XmlElement jarg1_, String jarg2);

  public static native long xml_element_append_child_value(long jarg1, XmlElement jarg1_, String jarg2, String jarg3);

  public static native long xml_element_prepend_child_value(long jarg1, XmlElement jarg1_, String jarg2, String jarg3);

  public static native boolean xml_element_set_child_value(long jarg1, XmlElement jarg1_, String jarg2, String jarg3);

  public static native boolean xml_element_set_name(long jarg1, XmlElement jarg1_, String jarg2);

  public static native boolean xml_element_set_value(long jarg1, XmlElement jarg1_, String jarg2);

  public static native long xml_element_append_child(long jarg1, XmlElement jarg1_, String jarg2);

  public static native long xml_element_prepend_child(long jarg1, XmlElement jarg1_, String jarg2);

  public static native long xml_element_append_copy(long jarg1, XmlElement jarg1_, long jarg2, XmlElement jarg2_);

  public static native long xml_element_prepend_copy(long jarg1, XmlElement jarg1_, long jarg2, XmlElement jarg2_);

  public static native void xml_element_remove_child__SWIG_0(long jarg1, XmlElement jarg1_, String jarg2);

  public static native void xml_element_remove_child__SWIG_1(long jarg1, XmlElement jarg1_, long jarg2, XmlElement jarg2_);

  public static native void delete_xml_element(long jarg1);

  public static native long new_continuous_resolver__SWIG_0(double jarg1);

  public static native long new_continuous_resolver__SWIG_1();

  public static native long new_continuous_resolver__SWIG_2(String jarg1, String jarg2, double jarg3);

  public static native long new_continuous_resolver__SWIG_3(String jarg1, String jarg2);

  public static native long new_continuous_resolver__SWIG_4(String jarg1, double jarg2);

  public static native long new_continuous_resolver__SWIG_5(String jarg1);

  public static native long continuous_resolver_results(long jarg1, ContinuousResolver jarg1_);

  public static native void delete_continuous_resolver(long jarg1);

  public static native long new_lost_error(String jarg1);

  public static native void delete_lost_error(long jarg1);

  public static native long new_timeout_error(String jarg1);

  public static native void delete_timeout_error(long jarg1);

  public static native long new_vectorf__SWIG_0();

  public static native long new_vectorf__SWIG_1(long jarg1);

  public static native long vectorf_size(long jarg1, VectorF jarg1_);

  public static native long vectorf_capacity(long jarg1, VectorF jarg1_);

  public static native void vectorf_reserve(long jarg1, VectorF jarg1_, long jarg2);

  public static native boolean vectorf_isEmpty(long jarg1, VectorF jarg1_);

  public static native void vectorf_clear(long jarg1, VectorF jarg1_);

  public static native void vectorf_add(long jarg1, VectorF jarg1_, float jarg2);

  public static native float vectorf_get(long jarg1, VectorF jarg1_, int jarg2);

  public static native void vectorf_set(long jarg1, VectorF jarg1_, int jarg2, float jarg3);

  public static native void delete_vectorf(long jarg1);

  public static native long new_vectord__SWIG_0();

  public static native long new_vectord__SWIG_1(long jarg1);

  public static native long vectord_size(long jarg1, VectorD jarg1_);

  public static native long vectord_capacity(long jarg1, VectorD jarg1_);

  public static native void vectord_reserve(long jarg1, VectorD jarg1_, long jarg2);

  public static native boolean vectord_isEmpty(long jarg1, VectorD jarg1_);

  public static native void vectord_clear(long jarg1, VectorD jarg1_);

  public static native void vectord_add(long jarg1, VectorD jarg1_, double jarg2);

  public static native double vectord_get(long jarg1, VectorD jarg1_, int jarg2);

  public static native void vectord_set(long jarg1, VectorD jarg1_, int jarg2, double jarg3);

  public static native void delete_vectord(long jarg1);

  public static native long new_vectorl__SWIG_0();

  public static native long new_vectorl__SWIG_1(long jarg1);

  public static native long vectorl_size(long jarg1, VectorL jarg1_);

  public static native long vectorl_capacity(long jarg1, VectorL jarg1_);

  public static native void vectorl_reserve(long jarg1, VectorL jarg1_, long jarg2);

  public static native boolean vectorl_isEmpty(long jarg1, VectorL jarg1_);

  public static native void vectorl_clear(long jarg1, VectorL jarg1_);

  public static native void vectorl_add(long jarg1, VectorL jarg1_, int jarg2);

  public static native int vectorl_get(long jarg1, VectorL jarg1_, int jarg2);

  public static native void vectorl_set(long jarg1, VectorL jarg1_, int jarg2, int jarg3);

  public static native void delete_vectorl(long jarg1);

  public static native long new_vectori__SWIG_0();

  public static native long new_vectori__SWIG_1(long jarg1);

  public static native long vectori_size(long jarg1, VectorI jarg1_);

  public static native long vectori_capacity(long jarg1, VectorI jarg1_);

  public static native void vectori_reserve(long jarg1, VectorI jarg1_, long jarg2);

  public static native boolean vectori_isEmpty(long jarg1, VectorI jarg1_);

  public static native void vectori_clear(long jarg1, VectorI jarg1_);

  public static native void vectori_add(long jarg1, VectorI jarg1_, int jarg2);

  public static native int vectori_get(long jarg1, VectorI jarg1_, int jarg2);

  public static native void vectori_set(long jarg1, VectorI jarg1_, int jarg2, int jarg3);

  public static native void delete_vectori(long jarg1);

  public static native long new_vectors__SWIG_0();

  public static native long new_vectors__SWIG_1(long jarg1);

  public static native long vectors_size(long jarg1, VectorS jarg1_);

  public static native long vectors_capacity(long jarg1, VectorS jarg1_);

  public static native void vectors_reserve(long jarg1, VectorS jarg1_, long jarg2);

  public static native boolean vectors_isEmpty(long jarg1, VectorS jarg1_);

  public static native void vectors_clear(long jarg1, VectorS jarg1_);

  public static native void vectors_add(long jarg1, VectorS jarg1_, short jarg2);

  public static native short vectors_get(long jarg1, VectorS jarg1_, int jarg2);

  public static native void vectors_set(long jarg1, VectorS jarg1_, int jarg2, short jarg3);

  public static native void delete_vectors(long jarg1);

  public static native long new_vectorstr__SWIG_0();

  public static native long new_vectorstr__SWIG_1(long jarg1);

  public static native long vectorstr_size(long jarg1, VectorStr jarg1_);

  public static native long vectorstr_capacity(long jarg1, VectorStr jarg1_);

  public static native void vectorstr_reserve(long jarg1, VectorStr jarg1_, long jarg2);

  public static native boolean vectorstr_isEmpty(long jarg1, VectorStr jarg1_);

  public static native void vectorstr_clear(long jarg1, VectorStr jarg1_);

  public static native void vectorstr_add(long jarg1, VectorStr jarg1_, String jarg2);

  public static native String vectorstr_get(long jarg1, VectorStr jarg1_, int jarg2);

  public static native void vectorstr_set(long jarg1, VectorStr jarg1_, int jarg2, String jarg3);

  public static native void delete_vectorstr(long jarg1);

  public static native long new_vectorinfo__SWIG_0();

  public static native long new_vectorinfo__SWIG_1(long jarg1);

  public static native long vectorinfo_size(long jarg1, VectorInfo jarg1_);

  public static native long vectorinfo_capacity(long jarg1, VectorInfo jarg1_);

  public static native void vectorinfo_reserve(long jarg1, VectorInfo jarg1_, long jarg2);

  public static native boolean vectorinfo_isEmpty(long jarg1, VectorInfo jarg1_);

  public static native void vectorinfo_clear(long jarg1, VectorInfo jarg1_);

  public static native void vectorinfo_add(long jarg1, VectorInfo jarg1_, long jarg2, StreamInfo jarg2_);

  public static native long vectorinfo_get(long jarg1, VectorInfo jarg1_, int jarg2);

  public static native void vectorinfo_set(long jarg1, VectorInfo jarg1_, int jarg2, long jarg3, StreamInfo jarg3_);

  public static native void delete_vectorinfo(long jarg1);
}
