/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.lsl;

public class StreamInfo
{
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected StreamInfo(long cPtr, boolean cMemoryOwn)
  {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StreamInfo obj)
  {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize()
  {
    delete();
  }

  public synchronized void delete()
  {
    if (swigCPtr != 0)
    {
      if (swigCMemOwn)
      {
        swigCMemOwn = false;
        LslAndroidJNI.delete_stream_info(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public StreamInfo(String name, String type, int channel_count, double nominal_srate, ChannelFormatT channel_format, String source_id)
  {
    this(LslAndroidJNI.new_stream_info__SWIG_0(name, type, channel_count, nominal_srate, channel_format.swigValue(), source_id), true);
  }

  public StreamInfo(String name, String type, int channel_count, double nominal_srate, ChannelFormatT channel_format)
  {
    this(LslAndroidJNI.new_stream_info__SWIG_1(name, type, channel_count, nominal_srate, channel_format.swigValue()), true);
  }

  public StreamInfo(String name, String type, int channel_count, double nominal_srate)
  {
    this(LslAndroidJNI.new_stream_info__SWIG_2(name, type, channel_count, nominal_srate), true);
  }

  public StreamInfo(String name, String type, int channel_count)
  {
    this(LslAndroidJNI.new_stream_info__SWIG_3(name, type, channel_count), true);
  }

  public StreamInfo(String name, String type)
  {
    this(LslAndroidJNI.new_stream_info__SWIG_4(name, type), true);
  }

  public StreamInfo(SWIGTYPE_p_lsl_streaminfo handle)
  {
    this(LslAndroidJNI.new_stream_info__SWIG_5(SWIGTYPE_p_lsl_streaminfo.getCPtr(handle)), true);
  }

  public String name()
  {
    return LslAndroidJNI.stream_info_name(swigCPtr, this);
  }

  public String type()
  {
    return LslAndroidJNI.stream_info_type(swigCPtr, this);
  }

  public int channel_count()
  {
    return LslAndroidJNI.stream_info_channel_count(swigCPtr, this);
  }

  public double nominal_srate()
  {
    return LslAndroidJNI.stream_info_nominal_srate(swigCPtr, this);
  }

  public ChannelFormatT channel_format()
  {
    return ChannelFormatT.swigToEnum(LslAndroidJNI.stream_info_channel_format(swigCPtr, this));
  }

  public String source_id()
  {
    return LslAndroidJNI.stream_info_source_id(swigCPtr, this);
  }

  public int version()
  {
    return LslAndroidJNI.stream_info_version(swigCPtr, this);
  }

  public double created_at()
  {
    return LslAndroidJNI.stream_info_created_at(swigCPtr, this);
  }

  public String uid()
  {
    return LslAndroidJNI.stream_info_uid(swigCPtr, this);
  }

  public String session_id()
  {
    return LslAndroidJNI.stream_info_session_id(swigCPtr, this);
  }

  public String hostname()
  {
    return LslAndroidJNI.stream_info_hostname(swigCPtr, this);
  }

  public XmlElement desc()
  {
    return new XmlElement(LslAndroidJNI.stream_info_desc(swigCPtr, this), true);
  }

  public String as_xml()
  {
    return LslAndroidJNI.stream_info_as_xml(swigCPtr, this);
  }

  public int channel_bytes()
  {
    return LslAndroidJNI.stream_info_channel_bytes(swigCPtr, this);
  }

  public int sample_bytes()
  {
    return LslAndroidJNI.stream_info_sample_bytes(swigCPtr, this);
  }

  public SWIGTYPE_p_lsl_streaminfo handle()
  {
    return new SWIGTYPE_p_lsl_streaminfo(LslAndroidJNI.stream_info_handle(swigCPtr, this), true);
  }

  public StreamInfo()
  {
    this(LslAndroidJNI.new_stream_info__SWIG_6(), true);
  }

  public StreamInfo(StreamInfo rhs)
  {
    this(LslAndroidJNI.new_stream_info__SWIG_7(StreamInfo.getCPtr(rhs), rhs), true);
  }

  public static StreamInfo from_xml(String xml)
  {
    return new StreamInfo(LslAndroidJNI.stream_info_from_xml(xml), true);
  }
}
