/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.lsl;

public class StreamInlet
{
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected StreamInlet(long cPtr, boolean cMemoryOwn)
  {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StreamInlet obj)
  {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize()
  {
    delete();
  }

  public synchronized void delete()
  {
    if (swigCPtr != 0)
    {
      if (swigCMemOwn)
      {
        swigCMemOwn = false;
        LslAndroidJNI.delete_stream_inlet(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public StreamInlet(StreamInfo info, int max_buflen, int max_chunklen, boolean recover)
  {
    this(LslAndroidJNI.new_stream_inlet__SWIG_0(StreamInfo.getCPtr(info), info, max_buflen, max_chunklen, recover), true);
  }

  public StreamInlet(StreamInfo info, int max_buflen, int max_chunklen)
  {
    this(LslAndroidJNI.new_stream_inlet__SWIG_1(StreamInfo.getCPtr(info), info, max_buflen, max_chunklen), true);
  }

  public StreamInlet(StreamInfo info, int max_buflen)
  {
    this(LslAndroidJNI.new_stream_inlet__SWIG_2(StreamInfo.getCPtr(info), info, max_buflen), true);
  }

  public StreamInlet(StreamInfo info)
  {
    this(LslAndroidJNI.new_stream_inlet__SWIG_3(StreamInfo.getCPtr(info), info), true);
  }

  public StreamInfo info(double timeout)
  {
    return new StreamInfo(LslAndroidJNI.stream_inlet_info__SWIG_0(swigCPtr, this, timeout), true);
  }

  public StreamInfo info()
  {
    return new StreamInfo(LslAndroidJNI.stream_inlet_info__SWIG_1(swigCPtr, this), true);
  }

  public void open_stream(double timeout)
  {
    LslAndroidJNI.stream_inlet_open_stream__SWIG_0(swigCPtr, this, timeout);
  }

  public void open_stream()
  {
    LslAndroidJNI.stream_inlet_open_stream__SWIG_1(swigCPtr, this);
  }

  public void close_stream()
  {
    LslAndroidJNI.stream_inlet_close_stream(swigCPtr, this);
  }

  public double time_correction(double timeout)
  {
    return LslAndroidJNI.stream_inlet_time_correction__SWIG_0(swigCPtr, this, timeout);
  }

  public double time_correction()
  {
    return LslAndroidJNI.stream_inlet_time_correction__SWIG_1(swigCPtr, this);
  }

  public double pull_sample(VectorF sample, double timeout)
  {
    return LslAndroidJNI.stream_inlet_pull_sample__SWIG_2(swigCPtr, this, VectorF.getCPtr(sample), sample, timeout);
  }

  public double pull_sample(VectorF sample)
  {
    return LslAndroidJNI.stream_inlet_pull_sample__SWIG_3(swigCPtr, this, VectorF.getCPtr(sample), sample);
  }

  public double pull_sample(VectorD sample, double timeout)
  {
    return LslAndroidJNI.stream_inlet_pull_sample__SWIG_4(swigCPtr, this, VectorD.getCPtr(sample), sample, timeout);
  }

  public double pull_sample(VectorD sample)
  {
    return LslAndroidJNI.stream_inlet_pull_sample__SWIG_5(swigCPtr, this, VectorD.getCPtr(sample), sample);
  }

  public double pull_sample(VectorL sample, double timeout)
  {
    return LslAndroidJNI.stream_inlet_pull_sample__SWIG_6(swigCPtr, this, VectorL.getCPtr(sample), sample, timeout);
  }

  public double pull_sample(VectorL sample)
  {
    return LslAndroidJNI.stream_inlet_pull_sample__SWIG_7(swigCPtr, this, VectorL.getCPtr(sample), sample);
  }

  public double pull_sample(VectorI sample, double timeout)
  {
    return LslAndroidJNI.stream_inlet_pull_sample__SWIG_8(swigCPtr, this, VectorI.getCPtr(sample), sample, timeout);
  }

  public double pull_sample(VectorI sample)
  {
    return LslAndroidJNI.stream_inlet_pull_sample__SWIG_9(swigCPtr, this, VectorI.getCPtr(sample), sample);
  }

  public double pull_sample(VectorS sample, double timeout)
  {
    return LslAndroidJNI.stream_inlet_pull_sample__SWIG_10(swigCPtr, this, VectorS.getCPtr(sample), sample, timeout);
  }

  public double pull_sample(VectorS sample)
  {
    return LslAndroidJNI.stream_inlet_pull_sample__SWIG_11(swigCPtr, this, VectorS.getCPtr(sample), sample);
  }

  public double pull_sample(SWIGTYPE_p_std__vectorT_char_t sample, double timeout)
  {
    return LslAndroidJNI.stream_inlet_pull_sample__SWIG_12(swigCPtr, this, SWIGTYPE_p_std__vectorT_char_t.getCPtr(sample), timeout);
  }

  public double pull_sample(SWIGTYPE_p_std__vectorT_char_t sample)
  {
    return LslAndroidJNI.stream_inlet_pull_sample__SWIG_13(swigCPtr, this, SWIGTYPE_p_std__vectorT_char_t.getCPtr(sample));
  }

  public double pull_sample(VectorStr sample, double timeout)
  {
    return LslAndroidJNI.stream_inlet_pull_sample__SWIG_14(swigCPtr, this, VectorStr.getCPtr(sample), sample, timeout);
  }

  public double pull_sample(VectorStr sample)
  {
    return LslAndroidJNI.stream_inlet_pull_sample__SWIG_15(swigCPtr, this, VectorStr.getCPtr(sample), sample);
  }

  public double pull_sample(SWIGTYPE_p_float buffer, int buffer_elements, double timeout)
  {
    return LslAndroidJNI.stream_inlet_pull_sample__SWIG_16(swigCPtr, this, SWIGTYPE_p_float.getCPtr(buffer), buffer_elements, timeout);
  }

  public double pull_sample(SWIGTYPE_p_float buffer, int buffer_elements)
  {
    return LslAndroidJNI.stream_inlet_pull_sample__SWIG_17(swigCPtr, this, SWIGTYPE_p_float.getCPtr(buffer), buffer_elements);
  }

  public double pull_sample(SWIGTYPE_p_double buffer, int buffer_elements, double timeout)
  {
    return LslAndroidJNI.stream_inlet_pull_sample__SWIG_18(swigCPtr, this, SWIGTYPE_p_double.getCPtr(buffer), buffer_elements, timeout);
  }

  public double pull_sample(SWIGTYPE_p_double buffer, int buffer_elements)
  {
    return LslAndroidJNI.stream_inlet_pull_sample__SWIG_19(swigCPtr, this, SWIGTYPE_p_double.getCPtr(buffer), buffer_elements);
  }

  public double pull_sample(SWIGTYPE_p_long buffer, int buffer_elements, double timeout)
  {
    return LslAndroidJNI.stream_inlet_pull_sample__SWIG_20(swigCPtr, this, SWIGTYPE_p_long.getCPtr(buffer), buffer_elements, timeout);
  }

  public double pull_sample(SWIGTYPE_p_long buffer, int buffer_elements)
  {
    return LslAndroidJNI.stream_inlet_pull_sample__SWIG_21(swigCPtr, this, SWIGTYPE_p_long.getCPtr(buffer), buffer_elements);
  }

  public double pull_sample(SWIGTYPE_p_int buffer, int buffer_elements, double timeout)
  {
    return LslAndroidJNI.stream_inlet_pull_sample__SWIG_22(swigCPtr, this, SWIGTYPE_p_int.getCPtr(buffer), buffer_elements, timeout);
  }

  public double pull_sample(SWIGTYPE_p_int buffer, int buffer_elements)
  {
    return LslAndroidJNI.stream_inlet_pull_sample__SWIG_23(swigCPtr, this, SWIGTYPE_p_int.getCPtr(buffer), buffer_elements);
  }

  public double pull_sample(SWIGTYPE_p_short buffer, int buffer_elements, double timeout)
  {
    return LslAndroidJNI.stream_inlet_pull_sample__SWIG_24(swigCPtr, this, SWIGTYPE_p_short.getCPtr(buffer), buffer_elements, timeout);
  }

  public double pull_sample(SWIGTYPE_p_short buffer, int buffer_elements)
  {
    return LslAndroidJNI.stream_inlet_pull_sample__SWIG_25(swigCPtr, this, SWIGTYPE_p_short.getCPtr(buffer), buffer_elements);
  }

  public double pull_sample(String buffer, int buffer_elements, double timeout)
  {
    return LslAndroidJNI.stream_inlet_pull_sample__SWIG_26(swigCPtr, this, buffer, buffer_elements, timeout);
  }

  public double pull_sample(String buffer, int buffer_elements)
  {
    return LslAndroidJNI.stream_inlet_pull_sample__SWIG_27(swigCPtr, this, buffer, buffer_elements);
  }

  public double pull_sample(SWIGTYPE_p_std__string buffer, int buffer_elements, double timeout)
  {
    return LslAndroidJNI.stream_inlet_pull_sample__SWIG_28(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(buffer), buffer_elements, timeout);
  }

  public double pull_sample(SWIGTYPE_p_std__string buffer, int buffer_elements)
  {
    return LslAndroidJNI.stream_inlet_pull_sample__SWIG_29(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(buffer), buffer_elements);
  }

  public double pull_numeric_raw(SWIGTYPE_p_void sample, int buffer_bytes, double timeout)
  {
    return LslAndroidJNI.stream_inlet_pull_numeric_raw__SWIG_0(swigCPtr, this, SWIGTYPE_p_void.getCPtr(sample), buffer_bytes, timeout);
  }

  public double pull_numeric_raw(SWIGTYPE_p_void sample, int buffer_bytes)
  {
    return LslAndroidJNI.stream_inlet_pull_numeric_raw__SWIG_1(swigCPtr, this, SWIGTYPE_p_void.getCPtr(sample), buffer_bytes);
  }

  public long pull_chunk_multiplexed(SWIGTYPE_p_float data_buffer, SWIGTYPE_p_double timestamp_buffer, long data_buffer_elements, long timestamp_buffer_elements, double timeout)
  {
    return LslAndroidJNI
        .stream_inlet_pull_chunk_multiplexed__SWIG_0(swigCPtr, this, SWIGTYPE_p_float.getCPtr(data_buffer), SWIGTYPE_p_double.getCPtr(timestamp_buffer), data_buffer_elements,
            timestamp_buffer_elements, timeout);
  }

  public long pull_chunk_multiplexed(SWIGTYPE_p_float data_buffer, SWIGTYPE_p_double timestamp_buffer, long data_buffer_elements, long timestamp_buffer_elements)
  {
    return LslAndroidJNI
        .stream_inlet_pull_chunk_multiplexed__SWIG_1(swigCPtr, this, SWIGTYPE_p_float.getCPtr(data_buffer), SWIGTYPE_p_double.getCPtr(timestamp_buffer), data_buffer_elements,
            timestamp_buffer_elements);
  }

  public long pull_chunk_multiplexed(SWIGTYPE_p_double data_buffer, SWIGTYPE_p_double timestamp_buffer, long data_buffer_elements, long timestamp_buffer_elements, double timeout)
  {
    return LslAndroidJNI
        .stream_inlet_pull_chunk_multiplexed__SWIG_2(swigCPtr, this, SWIGTYPE_p_double.getCPtr(data_buffer), SWIGTYPE_p_double.getCPtr(timestamp_buffer), data_buffer_elements,
            timestamp_buffer_elements, timeout);
  }

  public long pull_chunk_multiplexed(SWIGTYPE_p_double data_buffer, SWIGTYPE_p_double timestamp_buffer, long data_buffer_elements, long timestamp_buffer_elements)
  {
    return LslAndroidJNI
        .stream_inlet_pull_chunk_multiplexed__SWIG_3(swigCPtr, this, SWIGTYPE_p_double.getCPtr(data_buffer), SWIGTYPE_p_double.getCPtr(timestamp_buffer), data_buffer_elements,
            timestamp_buffer_elements);
  }

  public long pull_chunk_multiplexed(SWIGTYPE_p_long data_buffer, SWIGTYPE_p_double timestamp_buffer, long data_buffer_elements, long timestamp_buffer_elements, double timeout)
  {
    return LslAndroidJNI
        .stream_inlet_pull_chunk_multiplexed__SWIG_4(swigCPtr, this, SWIGTYPE_p_long.getCPtr(data_buffer), SWIGTYPE_p_double.getCPtr(timestamp_buffer), data_buffer_elements,
            timestamp_buffer_elements, timeout);
  }

  public long pull_chunk_multiplexed(SWIGTYPE_p_long data_buffer, SWIGTYPE_p_double timestamp_buffer, long data_buffer_elements, long timestamp_buffer_elements)
  {
    return LslAndroidJNI
        .stream_inlet_pull_chunk_multiplexed__SWIG_5(swigCPtr, this, SWIGTYPE_p_long.getCPtr(data_buffer), SWIGTYPE_p_double.getCPtr(timestamp_buffer), data_buffer_elements,
            timestamp_buffer_elements);
  }

  public long pull_chunk_multiplexed(SWIGTYPE_p_int data_buffer, SWIGTYPE_p_double timestamp_buffer, long data_buffer_elements, long timestamp_buffer_elements, double timeout)
  {
    return LslAndroidJNI
        .stream_inlet_pull_chunk_multiplexed__SWIG_6(swigCPtr, this, SWIGTYPE_p_int.getCPtr(data_buffer), SWIGTYPE_p_double.getCPtr(timestamp_buffer), data_buffer_elements,
            timestamp_buffer_elements, timeout);
  }

  public long pull_chunk_multiplexed(SWIGTYPE_p_int data_buffer, SWIGTYPE_p_double timestamp_buffer, long data_buffer_elements, long timestamp_buffer_elements)
  {
    return LslAndroidJNI
        .stream_inlet_pull_chunk_multiplexed__SWIG_7(swigCPtr, this, SWIGTYPE_p_int.getCPtr(data_buffer), SWIGTYPE_p_double.getCPtr(timestamp_buffer), data_buffer_elements,
            timestamp_buffer_elements);
  }

  public long pull_chunk_multiplexed(SWIGTYPE_p_short data_buffer, SWIGTYPE_p_double timestamp_buffer, long data_buffer_elements, long timestamp_buffer_elements, double timeout)
  {
    return LslAndroidJNI
        .stream_inlet_pull_chunk_multiplexed__SWIG_8(swigCPtr, this, SWIGTYPE_p_short.getCPtr(data_buffer), SWIGTYPE_p_double.getCPtr(timestamp_buffer), data_buffer_elements,
            timestamp_buffer_elements, timeout);
  }

  public long pull_chunk_multiplexed(SWIGTYPE_p_short data_buffer, SWIGTYPE_p_double timestamp_buffer, long data_buffer_elements, long timestamp_buffer_elements)
  {
    return LslAndroidJNI
        .stream_inlet_pull_chunk_multiplexed__SWIG_9(swigCPtr, this, SWIGTYPE_p_short.getCPtr(data_buffer), SWIGTYPE_p_double.getCPtr(timestamp_buffer), data_buffer_elements,
            timestamp_buffer_elements);
  }

  public long pull_chunk_multiplexed(String data_buffer, SWIGTYPE_p_double timestamp_buffer, long data_buffer_elements, long timestamp_buffer_elements, double timeout)
  {
    return LslAndroidJNI
        .stream_inlet_pull_chunk_multiplexed__SWIG_10(swigCPtr, this, data_buffer, SWIGTYPE_p_double.getCPtr(timestamp_buffer), data_buffer_elements, timestamp_buffer_elements,
            timeout);
  }

  public long pull_chunk_multiplexed(String data_buffer, SWIGTYPE_p_double timestamp_buffer, long data_buffer_elements, long timestamp_buffer_elements)
  {
    return LslAndroidJNI
        .stream_inlet_pull_chunk_multiplexed__SWIG_11(swigCPtr, this, data_buffer, SWIGTYPE_p_double.getCPtr(timestamp_buffer), data_buffer_elements, timestamp_buffer_elements);
  }

  public long pull_chunk_multiplexed(
      SWIGTYPE_p_std__string data_buffer, SWIGTYPE_p_double timestamp_buffer, long data_buffer_elements, long timestamp_buffer_elements, double timeout)
  {
    return LslAndroidJNI.stream_inlet_pull_chunk_multiplexed__SWIG_12(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(data_buffer), SWIGTYPE_p_double.getCPtr(timestamp_buffer),
        data_buffer_elements, timestamp_buffer_elements, timeout);
  }

  public long pull_chunk_multiplexed(SWIGTYPE_p_std__string data_buffer, SWIGTYPE_p_double timestamp_buffer, long data_buffer_elements, long timestamp_buffer_elements)
  {
    return LslAndroidJNI.stream_inlet_pull_chunk_multiplexed__SWIG_13(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(data_buffer), SWIGTYPE_p_double.getCPtr(timestamp_buffer),
        data_buffer_elements, timestamp_buffer_elements);
  }

  public long samples_available()
  {
    return LslAndroidJNI.stream_inlet_samples_available(swigCPtr, this);
  }

  public boolean was_clock_reset()
  {
    return LslAndroidJNI.stream_inlet_was_clock_reset(swigCPtr, this);
  }
}
