/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.lsl;

public class StreamOutlet
{
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected StreamOutlet(long cPtr, boolean cMemoryOwn)
  {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StreamOutlet obj)
  {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize()
  {
    delete();
  }

  public synchronized void delete()
  {
    if (swigCPtr != 0)
    {
      if (swigCMemOwn)
      {
        swigCMemOwn = false;
        LslAndroidJNI.delete_stream_outlet(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public StreamOutlet(StreamInfo info, int chunk_size, int max_buffered)
  {
    this(LslAndroidJNI.new_stream_outlet__SWIG_0(StreamInfo.getCPtr(info), info, chunk_size, max_buffered), true);
  }

  public StreamOutlet(StreamInfo info, int chunk_size)
  {
    this(LslAndroidJNI.new_stream_outlet__SWIG_1(StreamInfo.getCPtr(info), info, chunk_size), true);
  }

  public StreamOutlet(StreamInfo info)
  {
    this(LslAndroidJNI.new_stream_outlet__SWIG_2(StreamInfo.getCPtr(info), info), true);
  }

  public void push_sample(VectorF data, double timestamp, boolean pushthrough)
  {
    LslAndroidJNI.stream_outlet_push_sample__SWIG_3(swigCPtr, this, VectorF.getCPtr(data), data, timestamp, pushthrough);
  }

  public void push_sample(VectorF data, double timestamp)
  {
    LslAndroidJNI.stream_outlet_push_sample__SWIG_4(swigCPtr, this, VectorF.getCPtr(data), data, timestamp);
  }

  public void push_sample(VectorF data)
  {
    LslAndroidJNI.stream_outlet_push_sample__SWIG_5(swigCPtr, this, VectorF.getCPtr(data), data);
  }

  public void push_sample(VectorD data, double timestamp, boolean pushthrough)
  {
    LslAndroidJNI.stream_outlet_push_sample__SWIG_6(swigCPtr, this, VectorD.getCPtr(data), data, timestamp, pushthrough);
  }

  public void push_sample(VectorD data, double timestamp)
  {
    LslAndroidJNI.stream_outlet_push_sample__SWIG_7(swigCPtr, this, VectorD.getCPtr(data), data, timestamp);
  }

  public void push_sample(VectorD data)
  {
    LslAndroidJNI.stream_outlet_push_sample__SWIG_8(swigCPtr, this, VectorD.getCPtr(data), data);
  }

  public void push_sample(VectorL data, double timestamp, boolean pushthrough)
  {
    LslAndroidJNI.stream_outlet_push_sample__SWIG_9(swigCPtr, this, VectorL.getCPtr(data), data, timestamp, pushthrough);
  }

  public void push_sample(VectorL data, double timestamp)
  {
    LslAndroidJNI.stream_outlet_push_sample__SWIG_10(swigCPtr, this, VectorL.getCPtr(data), data, timestamp);
  }

  public void push_sample(VectorL data)
  {
    LslAndroidJNI.stream_outlet_push_sample__SWIG_11(swigCPtr, this, VectorL.getCPtr(data), data);
  }

  public void push_sample(VectorI data, double timestamp, boolean pushthrough)
  {
    LslAndroidJNI.stream_outlet_push_sample__SWIG_12(swigCPtr, this, VectorI.getCPtr(data), data, timestamp, pushthrough);
  }

  public void push_sample(VectorI data, double timestamp)
  {
    LslAndroidJNI.stream_outlet_push_sample__SWIG_13(swigCPtr, this, VectorI.getCPtr(data), data, timestamp);
  }

  public void push_sample(VectorI data)
  {
    LslAndroidJNI.stream_outlet_push_sample__SWIG_14(swigCPtr, this, VectorI.getCPtr(data), data);
  }

  public void push_sample(VectorS data, double timestamp, boolean pushthrough)
  {
    LslAndroidJNI.stream_outlet_push_sample__SWIG_15(swigCPtr, this, VectorS.getCPtr(data), data, timestamp, pushthrough);
  }

  public void push_sample(VectorS data, double timestamp)
  {
    LslAndroidJNI.stream_outlet_push_sample__SWIG_16(swigCPtr, this, VectorS.getCPtr(data), data, timestamp);
  }

  public void push_sample(VectorS data)
  {
    LslAndroidJNI.stream_outlet_push_sample__SWIG_17(swigCPtr, this, VectorS.getCPtr(data), data);
  }

  public void push_sample(SWIGTYPE_p_std__vectorT_char_t data, double timestamp, boolean pushthrough)
  {
    LslAndroidJNI.stream_outlet_push_sample__SWIG_18(swigCPtr, this, SWIGTYPE_p_std__vectorT_char_t.getCPtr(data), timestamp, pushthrough);
  }

  public void push_sample(SWIGTYPE_p_std__vectorT_char_t data, double timestamp)
  {
    LslAndroidJNI.stream_outlet_push_sample__SWIG_19(swigCPtr, this, SWIGTYPE_p_std__vectorT_char_t.getCPtr(data), timestamp);
  }

  public void push_sample(SWIGTYPE_p_std__vectorT_char_t data)
  {
    LslAndroidJNI.stream_outlet_push_sample__SWIG_20(swigCPtr, this, SWIGTYPE_p_std__vectorT_char_t.getCPtr(data));
  }

  public void push_sample(VectorStr data, double timestamp, boolean pushthrough)
  {
    LslAndroidJNI.stream_outlet_push_sample__SWIG_21(swigCPtr, this, VectorStr.getCPtr(data), data, timestamp, pushthrough);
  }

  public void push_sample(VectorStr data, double timestamp)
  {
    LslAndroidJNI.stream_outlet_push_sample__SWIG_22(swigCPtr, this, VectorStr.getCPtr(data), data, timestamp);
  }

  public void push_sample(VectorStr data)
  {
    LslAndroidJNI.stream_outlet_push_sample__SWIG_23(swigCPtr, this, VectorStr.getCPtr(data), data);
  }

  public void push_sample(SWIGTYPE_p_float data, double timestamp, boolean pushthrough)
  {
    LslAndroidJNI.stream_outlet_push_sample__SWIG_24(swigCPtr, this, SWIGTYPE_p_float.getCPtr(data), timestamp, pushthrough);
  }

  public void push_sample(SWIGTYPE_p_float data, double timestamp)
  {
    LslAndroidJNI.stream_outlet_push_sample__SWIG_25(swigCPtr, this, SWIGTYPE_p_float.getCPtr(data), timestamp);
  }

  public void push_sample(SWIGTYPE_p_float data)
  {
    LslAndroidJNI.stream_outlet_push_sample__SWIG_26(swigCPtr, this, SWIGTYPE_p_float.getCPtr(data));
  }

  public void push_sample(SWIGTYPE_p_double data, double timestamp, boolean pushthrough)
  {
    LslAndroidJNI.stream_outlet_push_sample__SWIG_27(swigCPtr, this, SWIGTYPE_p_double.getCPtr(data), timestamp, pushthrough);
  }

  public void push_sample(SWIGTYPE_p_double data, double timestamp)
  {
    LslAndroidJNI.stream_outlet_push_sample__SWIG_28(swigCPtr, this, SWIGTYPE_p_double.getCPtr(data), timestamp);
  }

  public void push_sample(SWIGTYPE_p_double data)
  {
    LslAndroidJNI.stream_outlet_push_sample__SWIG_29(swigCPtr, this, SWIGTYPE_p_double.getCPtr(data));
  }

  public void push_sample(SWIGTYPE_p_long data, double timestamp, boolean pushthrough)
  {
    LslAndroidJNI.stream_outlet_push_sample__SWIG_30(swigCPtr, this, SWIGTYPE_p_long.getCPtr(data), timestamp, pushthrough);
  }

  public void push_sample(SWIGTYPE_p_long data, double timestamp)
  {
    LslAndroidJNI.stream_outlet_push_sample__SWIG_31(swigCPtr, this, SWIGTYPE_p_long.getCPtr(data), timestamp);
  }

  public void push_sample(SWIGTYPE_p_long data)
  {
    LslAndroidJNI.stream_outlet_push_sample__SWIG_32(swigCPtr, this, SWIGTYPE_p_long.getCPtr(data));
  }

  public void push_sample(SWIGTYPE_p_int data, double timestamp, boolean pushthrough)
  {
    LslAndroidJNI.stream_outlet_push_sample__SWIG_33(swigCPtr, this, SWIGTYPE_p_int.getCPtr(data), timestamp, pushthrough);
  }

  public void push_sample(SWIGTYPE_p_int data, double timestamp)
  {
    LslAndroidJNI.stream_outlet_push_sample__SWIG_34(swigCPtr, this, SWIGTYPE_p_int.getCPtr(data), timestamp);
  }

  public void push_sample(SWIGTYPE_p_int data)
  {
    LslAndroidJNI.stream_outlet_push_sample__SWIG_35(swigCPtr, this, SWIGTYPE_p_int.getCPtr(data));
  }

  public void push_sample(SWIGTYPE_p_short data, double timestamp, boolean pushthrough)
  {
    LslAndroidJNI.stream_outlet_push_sample__SWIG_36(swigCPtr, this, SWIGTYPE_p_short.getCPtr(data), timestamp, pushthrough);
  }

  public void push_sample(SWIGTYPE_p_short data, double timestamp)
  {
    LslAndroidJNI.stream_outlet_push_sample__SWIG_37(swigCPtr, this, SWIGTYPE_p_short.getCPtr(data), timestamp);
  }

  public void push_sample(SWIGTYPE_p_short data)
  {
    LslAndroidJNI.stream_outlet_push_sample__SWIG_38(swigCPtr, this, SWIGTYPE_p_short.getCPtr(data));
  }

  public void push_sample(String data, double timestamp, boolean pushthrough)
  {
    LslAndroidJNI.stream_outlet_push_sample__SWIG_39(swigCPtr, this, data, timestamp, pushthrough);
  }

  public void push_sample(String data, double timestamp)
  {
    LslAndroidJNI.stream_outlet_push_sample__SWIG_40(swigCPtr, this, data, timestamp);
  }

  public void push_sample(String data)
  {
    LslAndroidJNI.stream_outlet_push_sample__SWIG_41(swigCPtr, this, data);
  }

  public void push_sample(SWIGTYPE_p_std__string data, double timestamp, boolean pushthrough)
  {
    LslAndroidJNI.stream_outlet_push_sample__SWIG_42(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(data), timestamp, pushthrough);
  }

  public void push_sample(SWIGTYPE_p_std__string data, double timestamp)
  {
    LslAndroidJNI.stream_outlet_push_sample__SWIG_43(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(data), timestamp);
  }

  public void push_sample(SWIGTYPE_p_std__string data)
  {
    LslAndroidJNI.stream_outlet_push_sample__SWIG_44(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(data));
  }

  public void push_numeric_raw(SWIGTYPE_p_void sample, double timestamp, boolean pushthrough)
  {
    LslAndroidJNI.stream_outlet_push_numeric_raw__SWIG_0(swigCPtr, this, SWIGTYPE_p_void.getCPtr(sample), timestamp, pushthrough);
  }

  public void push_numeric_raw(SWIGTYPE_p_void sample, double timestamp)
  {
    LslAndroidJNI.stream_outlet_push_numeric_raw__SWIG_1(swigCPtr, this, SWIGTYPE_p_void.getCPtr(sample), timestamp);
  }

  public void push_numeric_raw(SWIGTYPE_p_void sample)
  {
    LslAndroidJNI.stream_outlet_push_numeric_raw__SWIG_2(swigCPtr, this, SWIGTYPE_p_void.getCPtr(sample));
  }

  public void push_chunk_multiplexed(VectorF buffer, double timestamp, boolean pushthrough)
  {
    LslAndroidJNI.stream_outlet_push_chunk_multiplexed__SWIG_0(swigCPtr, this, VectorF.getCPtr(buffer), buffer, timestamp, pushthrough);
  }

  public void push_chunk_multiplexed(VectorF buffer, double timestamp)
  {
    LslAndroidJNI.stream_outlet_push_chunk_multiplexed__SWIG_1(swigCPtr, this, VectorF.getCPtr(buffer), buffer, timestamp);
  }

  public void push_chunk_multiplexed(VectorF buffer)
  {
    LslAndroidJNI.stream_outlet_push_chunk_multiplexed__SWIG_2(swigCPtr, this, VectorF.getCPtr(buffer), buffer);
  }

  public void push_chunk_multiplexed(VectorD buffer, double timestamp, boolean pushthrough)
  {
    LslAndroidJNI.stream_outlet_push_chunk_multiplexed__SWIG_3(swigCPtr, this, VectorD.getCPtr(buffer), buffer, timestamp, pushthrough);
  }

  public void push_chunk_multiplexed(VectorD buffer, double timestamp)
  {
    LslAndroidJNI.stream_outlet_push_chunk_multiplexed__SWIG_4(swigCPtr, this, VectorD.getCPtr(buffer), buffer, timestamp);
  }

  public void push_chunk_multiplexed(VectorD buffer)
  {
    LslAndroidJNI.stream_outlet_push_chunk_multiplexed__SWIG_5(swigCPtr, this, VectorD.getCPtr(buffer), buffer);
  }

  public void push_chunk_multiplexed(VectorL buffer, double timestamp, boolean pushthrough)
  {
    LslAndroidJNI.stream_outlet_push_chunk_multiplexed__SWIG_6(swigCPtr, this, VectorL.getCPtr(buffer), buffer, timestamp, pushthrough);
  }

  public void push_chunk_multiplexed(VectorL buffer, double timestamp)
  {
    LslAndroidJNI.stream_outlet_push_chunk_multiplexed__SWIG_7(swigCPtr, this, VectorL.getCPtr(buffer), buffer, timestamp);
  }

  public void push_chunk_multiplexed(VectorL buffer)
  {
    LslAndroidJNI.stream_outlet_push_chunk_multiplexed__SWIG_8(swigCPtr, this, VectorL.getCPtr(buffer), buffer);
  }

  public void push_chunk_multiplexed(VectorI buffer, double timestamp, boolean pushthrough)
  {
    LslAndroidJNI.stream_outlet_push_chunk_multiplexed__SWIG_9(swigCPtr, this, VectorI.getCPtr(buffer), buffer, timestamp, pushthrough);
  }

  public void push_chunk_multiplexed(VectorI buffer, double timestamp)
  {
    LslAndroidJNI.stream_outlet_push_chunk_multiplexed__SWIG_10(swigCPtr, this, VectorI.getCPtr(buffer), buffer, timestamp);
  }

  public void push_chunk_multiplexed(VectorI buffer)
  {
    LslAndroidJNI.stream_outlet_push_chunk_multiplexed__SWIG_11(swigCPtr, this, VectorI.getCPtr(buffer), buffer);
  }

  public void push_chunk_multiplexed(VectorS buffer, double timestamp, boolean pushthrough)
  {
    LslAndroidJNI.stream_outlet_push_chunk_multiplexed__SWIG_12(swigCPtr, this, VectorS.getCPtr(buffer), buffer, timestamp, pushthrough);
  }

  public void push_chunk_multiplexed(VectorS buffer, double timestamp)
  {
    LslAndroidJNI.stream_outlet_push_chunk_multiplexed__SWIG_13(swigCPtr, this, VectorS.getCPtr(buffer), buffer, timestamp);
  }

  public void push_chunk_multiplexed(VectorS buffer)
  {
    LslAndroidJNI.stream_outlet_push_chunk_multiplexed__SWIG_14(swigCPtr, this, VectorS.getCPtr(buffer), buffer);
  }

  public void push_chunk_multiplexed(SWIGTYPE_p_std__vectorT_char_t buffer, double timestamp, boolean pushthrough)
  {
    LslAndroidJNI.stream_outlet_push_chunk_multiplexed__SWIG_15(swigCPtr, this, SWIGTYPE_p_std__vectorT_char_t.getCPtr(buffer), timestamp, pushthrough);
  }

  public void push_chunk_multiplexed(SWIGTYPE_p_std__vectorT_char_t buffer, double timestamp)
  {
    LslAndroidJNI.stream_outlet_push_chunk_multiplexed__SWIG_16(swigCPtr, this, SWIGTYPE_p_std__vectorT_char_t.getCPtr(buffer), timestamp);
  }

  public void push_chunk_multiplexed(SWIGTYPE_p_std__vectorT_char_t buffer)
  {
    LslAndroidJNI.stream_outlet_push_chunk_multiplexed__SWIG_17(swigCPtr, this, SWIGTYPE_p_std__vectorT_char_t.getCPtr(buffer));
  }

  public void push_chunk_multiplexed(VectorStr buffer, double timestamp, boolean pushthrough)
  {
    LslAndroidJNI.stream_outlet_push_chunk_multiplexed__SWIG_18(swigCPtr, this, VectorStr.getCPtr(buffer), buffer, timestamp, pushthrough);
  }

  public void push_chunk_multiplexed(VectorStr buffer, double timestamp)
  {
    LslAndroidJNI.stream_outlet_push_chunk_multiplexed__SWIG_19(swigCPtr, this, VectorStr.getCPtr(buffer), buffer, timestamp);
  }

  public void push_chunk_multiplexed(VectorStr buffer)
  {
    LslAndroidJNI.stream_outlet_push_chunk_multiplexed__SWIG_20(swigCPtr, this, VectorStr.getCPtr(buffer), buffer);
  }

  public void push_chunk_multiplexed(VectorF buffer, VectorD timestamps, boolean pushthrough)
  {
    LslAndroidJNI.stream_outlet_push_chunk_multiplexed__SWIG_21(swigCPtr, this, VectorF.getCPtr(buffer), buffer, VectorD.getCPtr(timestamps), timestamps, pushthrough);
  }

  public void push_chunk_multiplexed(VectorF buffer, VectorD timestamps)
  {
    LslAndroidJNI.stream_outlet_push_chunk_multiplexed__SWIG_22(swigCPtr, this, VectorF.getCPtr(buffer), buffer, VectorD.getCPtr(timestamps), timestamps);
  }

  public void push_chunk_multiplexed(VectorD buffer, VectorD timestamps, boolean pushthrough)
  {
    LslAndroidJNI.stream_outlet_push_chunk_multiplexed__SWIG_23(swigCPtr, this, VectorD.getCPtr(buffer), buffer, VectorD.getCPtr(timestamps), timestamps, pushthrough);
  }

  public void push_chunk_multiplexed(VectorD buffer, VectorD timestamps)
  {
    LslAndroidJNI.stream_outlet_push_chunk_multiplexed__SWIG_24(swigCPtr, this, VectorD.getCPtr(buffer), buffer, VectorD.getCPtr(timestamps), timestamps);
  }

  public void push_chunk_multiplexed(VectorL buffer, VectorD timestamps, boolean pushthrough)
  {
    LslAndroidJNI.stream_outlet_push_chunk_multiplexed__SWIG_25(swigCPtr, this, VectorL.getCPtr(buffer), buffer, VectorD.getCPtr(timestamps), timestamps, pushthrough);
  }

  public void push_chunk_multiplexed(VectorL buffer, VectorD timestamps)
  {
    LslAndroidJNI.stream_outlet_push_chunk_multiplexed__SWIG_26(swigCPtr, this, VectorL.getCPtr(buffer), buffer, VectorD.getCPtr(timestamps), timestamps);
  }

  public void push_chunk_multiplexed(VectorI buffer, VectorD timestamps, boolean pushthrough)
  {
    LslAndroidJNI.stream_outlet_push_chunk_multiplexed__SWIG_27(swigCPtr, this, VectorI.getCPtr(buffer), buffer, VectorD.getCPtr(timestamps), timestamps, pushthrough);
  }

  public void push_chunk_multiplexed(VectorI buffer, VectorD timestamps)
  {
    LslAndroidJNI.stream_outlet_push_chunk_multiplexed__SWIG_28(swigCPtr, this, VectorI.getCPtr(buffer), buffer, VectorD.getCPtr(timestamps), timestamps);
  }

  public void push_chunk_multiplexed(VectorS buffer, VectorD timestamps, boolean pushthrough)
  {
    LslAndroidJNI.stream_outlet_push_chunk_multiplexed__SWIG_29(swigCPtr, this, VectorS.getCPtr(buffer), buffer, VectorD.getCPtr(timestamps), timestamps, pushthrough);
  }

  public void push_chunk_multiplexed(VectorS buffer, VectorD timestamps)
  {
    LslAndroidJNI.stream_outlet_push_chunk_multiplexed__SWIG_30(swigCPtr, this, VectorS.getCPtr(buffer), buffer, VectorD.getCPtr(timestamps), timestamps);
  }

  public void push_chunk_multiplexed(SWIGTYPE_p_std__vectorT_char_t buffer, VectorD timestamps, boolean pushthrough)
  {
    LslAndroidJNI
        .stream_outlet_push_chunk_multiplexed__SWIG_31(swigCPtr, this, SWIGTYPE_p_std__vectorT_char_t.getCPtr(buffer), VectorD.getCPtr(timestamps), timestamps, pushthrough);
  }

  public void push_chunk_multiplexed(SWIGTYPE_p_std__vectorT_char_t buffer, VectorD timestamps)
  {
    LslAndroidJNI.stream_outlet_push_chunk_multiplexed__SWIG_32(swigCPtr, this, SWIGTYPE_p_std__vectorT_char_t.getCPtr(buffer), VectorD.getCPtr(timestamps), timestamps);
  }

  public void push_chunk_multiplexed(VectorStr buffer, VectorD timestamps, boolean pushthrough)
  {
    LslAndroidJNI.stream_outlet_push_chunk_multiplexed__SWIG_33(swigCPtr, this, VectorStr.getCPtr(buffer), buffer, VectorD.getCPtr(timestamps), timestamps, pushthrough);
  }

  public void push_chunk_multiplexed(VectorStr buffer, VectorD timestamps)
  {
    LslAndroidJNI.stream_outlet_push_chunk_multiplexed__SWIG_34(swigCPtr, this, VectorStr.getCPtr(buffer), buffer, VectorD.getCPtr(timestamps), timestamps);
  }

  public void push_chunk_multiplexed(SWIGTYPE_p_float buffer, long buffer_elements, double timestamp, boolean pushthrough)
  {
    LslAndroidJNI.stream_outlet_push_chunk_multiplexed__SWIG_35(swigCPtr, this, SWIGTYPE_p_float.getCPtr(buffer), buffer_elements, timestamp, pushthrough);
  }

  public void push_chunk_multiplexed(SWIGTYPE_p_float buffer, long buffer_elements, double timestamp)
  {
    LslAndroidJNI.stream_outlet_push_chunk_multiplexed__SWIG_36(swigCPtr, this, SWIGTYPE_p_float.getCPtr(buffer), buffer_elements, timestamp);
  }

  public void push_chunk_multiplexed(SWIGTYPE_p_float buffer, long buffer_elements)
  {
    LslAndroidJNI.stream_outlet_push_chunk_multiplexed__SWIG_37(swigCPtr, this, SWIGTYPE_p_float.getCPtr(buffer), buffer_elements);
  }

  public void push_chunk_multiplexed(SWIGTYPE_p_double buffer, long buffer_elements, double timestamp, boolean pushthrough)
  {
    LslAndroidJNI.stream_outlet_push_chunk_multiplexed__SWIG_38(swigCPtr, this, SWIGTYPE_p_double.getCPtr(buffer), buffer_elements, timestamp, pushthrough);
  }

  public void push_chunk_multiplexed(SWIGTYPE_p_double buffer, long buffer_elements, double timestamp)
  {
    LslAndroidJNI.stream_outlet_push_chunk_multiplexed__SWIG_39(swigCPtr, this, SWIGTYPE_p_double.getCPtr(buffer), buffer_elements, timestamp);
  }

  public void push_chunk_multiplexed(SWIGTYPE_p_double buffer, long buffer_elements)
  {
    LslAndroidJNI.stream_outlet_push_chunk_multiplexed__SWIG_40(swigCPtr, this, SWIGTYPE_p_double.getCPtr(buffer), buffer_elements);
  }

  public void push_chunk_multiplexed(SWIGTYPE_p_long buffer, long buffer_elements, double timestamp, boolean pushthrough)
  {
    LslAndroidJNI.stream_outlet_push_chunk_multiplexed__SWIG_41(swigCPtr, this, SWIGTYPE_p_long.getCPtr(buffer), buffer_elements, timestamp, pushthrough);
  }

  public void push_chunk_multiplexed(SWIGTYPE_p_long buffer, long buffer_elements, double timestamp)
  {
    LslAndroidJNI.stream_outlet_push_chunk_multiplexed__SWIG_42(swigCPtr, this, SWIGTYPE_p_long.getCPtr(buffer), buffer_elements, timestamp);
  }

  public void push_chunk_multiplexed(SWIGTYPE_p_long buffer, long buffer_elements)
  {
    LslAndroidJNI.stream_outlet_push_chunk_multiplexed__SWIG_43(swigCPtr, this, SWIGTYPE_p_long.getCPtr(buffer), buffer_elements);
  }

  public void push_chunk_multiplexed(SWIGTYPE_p_int buffer, long buffer_elements, double timestamp, boolean pushthrough)
  {
    LslAndroidJNI.stream_outlet_push_chunk_multiplexed__SWIG_44(swigCPtr, this, SWIGTYPE_p_int.getCPtr(buffer), buffer_elements, timestamp, pushthrough);
  }

  public void push_chunk_multiplexed(SWIGTYPE_p_int buffer, long buffer_elements, double timestamp)
  {
    LslAndroidJNI.stream_outlet_push_chunk_multiplexed__SWIG_45(swigCPtr, this, SWIGTYPE_p_int.getCPtr(buffer), buffer_elements, timestamp);
  }

  public void push_chunk_multiplexed(SWIGTYPE_p_int buffer, long buffer_elements)
  {
    LslAndroidJNI.stream_outlet_push_chunk_multiplexed__SWIG_46(swigCPtr, this, SWIGTYPE_p_int.getCPtr(buffer), buffer_elements);
  }

  public void push_chunk_multiplexed(SWIGTYPE_p_short buffer, long buffer_elements, double timestamp, boolean pushthrough)
  {
    LslAndroidJNI.stream_outlet_push_chunk_multiplexed__SWIG_47(swigCPtr, this, SWIGTYPE_p_short.getCPtr(buffer), buffer_elements, timestamp, pushthrough);
  }

  public void push_chunk_multiplexed(SWIGTYPE_p_short buffer, long buffer_elements, double timestamp)
  {
    LslAndroidJNI.stream_outlet_push_chunk_multiplexed__SWIG_48(swigCPtr, this, SWIGTYPE_p_short.getCPtr(buffer), buffer_elements, timestamp);
  }

  public void push_chunk_multiplexed(SWIGTYPE_p_short buffer, long buffer_elements)
  {
    LslAndroidJNI.stream_outlet_push_chunk_multiplexed__SWIG_49(swigCPtr, this, SWIGTYPE_p_short.getCPtr(buffer), buffer_elements);
  }

  public void push_chunk_multiplexed(String buffer, long buffer_elements, double timestamp, boolean pushthrough)
  {
    LslAndroidJNI.stream_outlet_push_chunk_multiplexed__SWIG_50(swigCPtr, this, buffer, buffer_elements, timestamp, pushthrough);
  }

  public void push_chunk_multiplexed(String buffer, long buffer_elements, double timestamp)
  {
    LslAndroidJNI.stream_outlet_push_chunk_multiplexed__SWIG_51(swigCPtr, this, buffer, buffer_elements, timestamp);
  }

  public void push_chunk_multiplexed(String buffer, long buffer_elements)
  {
    LslAndroidJNI.stream_outlet_push_chunk_multiplexed__SWIG_52(swigCPtr, this, buffer, buffer_elements);
  }

  public void push_chunk_multiplexed(SWIGTYPE_p_std__string buffer, long buffer_elements, double timestamp, boolean pushthrough)
  {
    LslAndroidJNI.stream_outlet_push_chunk_multiplexed__SWIG_53(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(buffer), buffer_elements, timestamp, pushthrough);
  }

  public void push_chunk_multiplexed(SWIGTYPE_p_std__string buffer, long buffer_elements, double timestamp)
  {
    LslAndroidJNI.stream_outlet_push_chunk_multiplexed__SWIG_54(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(buffer), buffer_elements, timestamp);
  }

  public void push_chunk_multiplexed(SWIGTYPE_p_std__string buffer, long buffer_elements)
  {
    LslAndroidJNI.stream_outlet_push_chunk_multiplexed__SWIG_55(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(buffer), buffer_elements);
  }

  public void push_chunk_multiplexed(SWIGTYPE_p_float data_buffer, SWIGTYPE_p_double timestamp_buffer, long data_buffer_elements, boolean pushthrough)
  {
    LslAndroidJNI
        .stream_outlet_push_chunk_multiplexed__SWIG_56(swigCPtr, this, SWIGTYPE_p_float.getCPtr(data_buffer), SWIGTYPE_p_double.getCPtr(timestamp_buffer), data_buffer_elements,
            pushthrough);
  }

  public void push_chunk_multiplexed(SWIGTYPE_p_float data_buffer, SWIGTYPE_p_double timestamp_buffer, long data_buffer_elements)
  {
    LslAndroidJNI
        .stream_outlet_push_chunk_multiplexed__SWIG_57(swigCPtr, this, SWIGTYPE_p_float.getCPtr(data_buffer), SWIGTYPE_p_double.getCPtr(timestamp_buffer), data_buffer_elements);
  }

  public void push_chunk_multiplexed(SWIGTYPE_p_double data_buffer, SWIGTYPE_p_double timestamp_buffer, long data_buffer_elements, boolean pushthrough)
  {
    LslAndroidJNI
        .stream_outlet_push_chunk_multiplexed__SWIG_58(swigCPtr, this, SWIGTYPE_p_double.getCPtr(data_buffer), SWIGTYPE_p_double.getCPtr(timestamp_buffer), data_buffer_elements,
            pushthrough);
  }

  public void push_chunk_multiplexed(SWIGTYPE_p_double data_buffer, SWIGTYPE_p_double timestamp_buffer, long data_buffer_elements)
  {
    LslAndroidJNI
        .stream_outlet_push_chunk_multiplexed__SWIG_59(swigCPtr, this, SWIGTYPE_p_double.getCPtr(data_buffer), SWIGTYPE_p_double.getCPtr(timestamp_buffer), data_buffer_elements);
  }

  public void push_chunk_multiplexed(SWIGTYPE_p_long data_buffer, SWIGTYPE_p_double timestamp_buffer, long data_buffer_elements, boolean pushthrough)
  {
    LslAndroidJNI
        .stream_outlet_push_chunk_multiplexed__SWIG_60(swigCPtr, this, SWIGTYPE_p_long.getCPtr(data_buffer), SWIGTYPE_p_double.getCPtr(timestamp_buffer), data_buffer_elements,
            pushthrough);
  }

  public void push_chunk_multiplexed(SWIGTYPE_p_long data_buffer, SWIGTYPE_p_double timestamp_buffer, long data_buffer_elements)
  {
    LslAndroidJNI
        .stream_outlet_push_chunk_multiplexed__SWIG_61(swigCPtr, this, SWIGTYPE_p_long.getCPtr(data_buffer), SWIGTYPE_p_double.getCPtr(timestamp_buffer), data_buffer_elements);
  }

  public void push_chunk_multiplexed(SWIGTYPE_p_int data_buffer, SWIGTYPE_p_double timestamp_buffer, long data_buffer_elements, boolean pushthrough)
  {
    LslAndroidJNI
        .stream_outlet_push_chunk_multiplexed__SWIG_62(swigCPtr, this, SWIGTYPE_p_int.getCPtr(data_buffer), SWIGTYPE_p_double.getCPtr(timestamp_buffer), data_buffer_elements,
            pushthrough);
  }

  public void push_chunk_multiplexed(SWIGTYPE_p_int data_buffer, SWIGTYPE_p_double timestamp_buffer, long data_buffer_elements)
  {
    LslAndroidJNI
        .stream_outlet_push_chunk_multiplexed__SWIG_63(swigCPtr, this, SWIGTYPE_p_int.getCPtr(data_buffer), SWIGTYPE_p_double.getCPtr(timestamp_buffer), data_buffer_elements);
  }

  public void push_chunk_multiplexed(SWIGTYPE_p_short data_buffer, SWIGTYPE_p_double timestamp_buffer, long data_buffer_elements, boolean pushthrough)
  {
    LslAndroidJNI
        .stream_outlet_push_chunk_multiplexed__SWIG_64(swigCPtr, this, SWIGTYPE_p_short.getCPtr(data_buffer), SWIGTYPE_p_double.getCPtr(timestamp_buffer), data_buffer_elements,
            pushthrough);
  }

  public void push_chunk_multiplexed(SWIGTYPE_p_short data_buffer, SWIGTYPE_p_double timestamp_buffer, long data_buffer_elements)
  {
    LslAndroidJNI
        .stream_outlet_push_chunk_multiplexed__SWIG_65(swigCPtr, this, SWIGTYPE_p_short.getCPtr(data_buffer), SWIGTYPE_p_double.getCPtr(timestamp_buffer), data_buffer_elements);
  }

  public void push_chunk_multiplexed(String data_buffer, SWIGTYPE_p_double timestamp_buffer, long data_buffer_elements, boolean pushthrough)
  {
    LslAndroidJNI.stream_outlet_push_chunk_multiplexed__SWIG_66(swigCPtr, this, data_buffer, SWIGTYPE_p_double.getCPtr(timestamp_buffer), data_buffer_elements, pushthrough);
  }

  public void push_chunk_multiplexed(String data_buffer, SWIGTYPE_p_double timestamp_buffer, long data_buffer_elements)
  {
    LslAndroidJNI.stream_outlet_push_chunk_multiplexed__SWIG_67(swigCPtr, this, data_buffer, SWIGTYPE_p_double.getCPtr(timestamp_buffer), data_buffer_elements);
  }

  public void push_chunk_multiplexed(SWIGTYPE_p_std__string data_buffer, SWIGTYPE_p_double timestamp_buffer, long data_buffer_elements, boolean pushthrough)
  {
    LslAndroidJNI.stream_outlet_push_chunk_multiplexed__SWIG_68(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(data_buffer), SWIGTYPE_p_double.getCPtr(timestamp_buffer),
        data_buffer_elements, pushthrough);
  }

  public void push_chunk_multiplexed(SWIGTYPE_p_std__string data_buffer, SWIGTYPE_p_double timestamp_buffer, long data_buffer_elements)
  {
    LslAndroidJNI.stream_outlet_push_chunk_multiplexed__SWIG_69(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(data_buffer), SWIGTYPE_p_double.getCPtr(timestamp_buffer),
        data_buffer_elements);
  }

  public boolean have_consumers()
  {
    return LslAndroidJNI.stream_outlet_have_consumers(swigCPtr, this);
  }

  public boolean wait_for_consumers(double timeout)
  {
    return LslAndroidJNI.stream_outlet_wait_for_consumers(swigCPtr, this, timeout);
  }

  public StreamInfo info()
  {
    return new StreamInfo(LslAndroidJNI.stream_outlet_info(swigCPtr, this), true);
  }
}
