/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.lsl;

public class VectorI
{
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VectorI(long cPtr, boolean cMemoryOwn)
  {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VectorI obj)
  {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize()
  {
    delete();
  }

  public synchronized void delete()
  {
    if (swigCPtr != 0)
    {
      if (swigCMemOwn)
      {
        swigCMemOwn = false;
        LslAndroidJNI.delete_vectori(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VectorI()
  {
    this(LslAndroidJNI.new_vectori__SWIG_0(), true);
  }

  public VectorI(long n)
  {
    this(LslAndroidJNI.new_vectori__SWIG_1(n), true);
  }

  public long size()
  {
    return LslAndroidJNI.vectori_size(swigCPtr, this);
  }

  public long capacity()
  {
    return LslAndroidJNI.vectori_capacity(swigCPtr, this);
  }

  public void reserve(long n)
  {
    LslAndroidJNI.vectori_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty()
  {
    return LslAndroidJNI.vectori_isEmpty(swigCPtr, this);
  }

  public void clear()
  {
    LslAndroidJNI.vectori_clear(swigCPtr, this);
  }

  public void add(int x)
  {
    LslAndroidJNI.vectori_add(swigCPtr, this, x);
  }

  public int get(int i)
  {
    return LslAndroidJNI.vectori_get(swigCPtr, this, i);
  }

  public void set(int i, int val)
  {
    LslAndroidJNI.vectori_set(swigCPtr, this, i, val);
  }
}
