/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.lsl;

public class VectorStr
{
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VectorStr(long cPtr, boolean cMemoryOwn)
  {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VectorStr obj)
  {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize()
  {
    delete();
  }

  public synchronized void delete()
  {
    if (swigCPtr != 0)
    {
      if (swigCMemOwn)
      {
        swigCMemOwn = false;
        LslAndroidJNI.delete_vectorstr(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VectorStr()
  {
    this(LslAndroidJNI.new_vectorstr__SWIG_0(), true);
  }

  public VectorStr(long n)
  {
    this(LslAndroidJNI.new_vectorstr__SWIG_1(n), true);
  }

  public long size()
  {
    return LslAndroidJNI.vectorstr_size(swigCPtr, this);
  }

  public long capacity()
  {
    return LslAndroidJNI.vectorstr_capacity(swigCPtr, this);
  }

  public void reserve(long n)
  {
    LslAndroidJNI.vectorstr_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty()
  {
    return LslAndroidJNI.vectorstr_isEmpty(swigCPtr, this);
  }

  public void clear()
  {
    LslAndroidJNI.vectorstr_clear(swigCPtr, this);
  }

  public void add(String x)
  {
    LslAndroidJNI.vectorstr_add(swigCPtr, this, x);
  }

  public String get(int i)
  {
    return LslAndroidJNI.vectorstr_get(swigCPtr, this, i);
  }

  public void set(int i, String val)
  {
    LslAndroidJNI.vectorstr_set(swigCPtr, this, i, val);
  }
}
