/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.lsl;

public class VectorS
{
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VectorS(long cPtr, boolean cMemoryOwn)
  {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VectorS obj)
  {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize()
  {
    delete();
  }

  public synchronized void delete()
  {
    if (swigCPtr != 0)
    {
      if (swigCMemOwn)
      {
        swigCMemOwn = false;
        LslAndroidJNI.delete_vectors(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VectorS()
  {
    this(LslAndroidJNI.new_vectors__SWIG_0(), true);
  }

  public VectorS(long n)
  {
    this(LslAndroidJNI.new_vectors__SWIG_1(n), true);
  }

  public long size()
  {
    return LslAndroidJNI.vectors_size(swigCPtr, this);
  }

  public long capacity()
  {
    return LslAndroidJNI.vectors_capacity(swigCPtr, this);
  }

  public void reserve(long n)
  {
    LslAndroidJNI.vectors_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty()
  {
    return LslAndroidJNI.vectors_isEmpty(swigCPtr, this);
  }

  public void clear()
  {
    LslAndroidJNI.vectors_clear(swigCPtr, this);
  }

  public void add(short x)
  {
    LslAndroidJNI.vectors_add(swigCPtr, this, x);
  }

  public short get(int i)
  {
    return LslAndroidJNI.vectors_get(swigCPtr, this, i);
  }

  public void set(int i, short val)
  {
    LslAndroidJNI.vectors_set(swigCPtr, this, i, val);
  }
}
