/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.lsl;

public class VectorF
{
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VectorF(long cPtr, boolean cMemoryOwn)
  {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VectorF obj)
  {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize()
  {
    delete();
  }

  public synchronized void delete()
  {
    if (swigCPtr != 0)
    {
      if (swigCMemOwn)
      {
        swigCMemOwn = false;
        LslAndroidJNI.delete_vectorf(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VectorF()
  {
    this(LslAndroidJNI.new_vectorf__SWIG_0(), true);
  }

  public VectorF(long n)
  {
    this(LslAndroidJNI.new_vectorf__SWIG_1(n), true);
  }

  public long size()
  {
    return LslAndroidJNI.vectorf_size(swigCPtr, this);
  }

  public long capacity()
  {
    return LslAndroidJNI.vectorf_capacity(swigCPtr, this);
  }

  public void reserve(long n)
  {
    LslAndroidJNI.vectorf_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty()
  {
    return LslAndroidJNI.vectorf_isEmpty(swigCPtr, this);
  }

  public void clear()
  {
    LslAndroidJNI.vectorf_clear(swigCPtr, this);
  }

  public void add(float x)
  {
    LslAndroidJNI.vectorf_add(swigCPtr, this, x);
  }

  public float get(int i)
  {
    return LslAndroidJNI.vectorf_get(swigCPtr, this, i);
  }

  public void set(int i, float val)
  {
    LslAndroidJNI.vectorf_set(swigCPtr, this, i, val);
  }
}
