/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.lsl;

public class VectorInfo
{
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VectorInfo(long cPtr, boolean cMemoryOwn)
  {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VectorInfo obj)
  {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize()
  {
    delete();
  }

  public synchronized void delete()
  {
    if (swigCPtr != 0)
    {
      if (swigCMemOwn)
      {
        swigCMemOwn = false;
        LslAndroidJNI.delete_vectorinfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VectorInfo()
  {
    this(LslAndroidJNI.new_vectorinfo__SWIG_0(), true);
  }

  public VectorInfo(long n)
  {
    this(LslAndroidJNI.new_vectorinfo__SWIG_1(n), true);
  }

  public long size()
  {
    return LslAndroidJNI.vectorinfo_size(swigCPtr, this);
  }

  public long capacity()
  {
    return LslAndroidJNI.vectorinfo_capacity(swigCPtr, this);
  }

  public void reserve(long n)
  {
    LslAndroidJNI.vectorinfo_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty()
  {
    return LslAndroidJNI.vectorinfo_isEmpty(swigCPtr, this);
  }

  public void clear()
  {
    LslAndroidJNI.vectorinfo_clear(swigCPtr, this);
  }

  public void add(StreamInfo x)
  {
    LslAndroidJNI.vectorinfo_add(swigCPtr, this, StreamInfo.getCPtr(x), x);
  }

  public StreamInfo get(int i)
  {
    return new StreamInfo(LslAndroidJNI.vectorinfo_get(swigCPtr, this, i), false);
  }

  public void set(int i, StreamInfo val)
  {
    LslAndroidJNI.vectorinfo_set(swigCPtr, this, i, StreamInfo.getCPtr(val), val);
  }
}
