/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.lsl;

public class VectorD
{
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VectorD(long cPtr, boolean cMemoryOwn)
  {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VectorD obj)
  {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize()
  {
    delete();
  }

  public synchronized void delete()
  {
    if (swigCPtr != 0)
    {
      if (swigCMemOwn)
      {
        swigCMemOwn = false;
        LslAndroidJNI.delete_vectord(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VectorD()
  {
    this(LslAndroidJNI.new_vectord__SWIG_0(), true);
  }

  public VectorD(long n)
  {
    this(LslAndroidJNI.new_vectord__SWIG_1(n), true);
  }

  public long size()
  {
    return LslAndroidJNI.vectord_size(swigCPtr, this);
  }

  public long capacity()
  {
    return LslAndroidJNI.vectord_capacity(swigCPtr, this);
  }

  public void reserve(long n)
  {
    LslAndroidJNI.vectord_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty()
  {
    return LslAndroidJNI.vectord_isEmpty(swigCPtr, this);
  }

  public void clear()
  {
    LslAndroidJNI.vectord_clear(swigCPtr, this);
  }

  public void add(double x)
  {
    LslAndroidJNI.vectord_add(swigCPtr, this, x);
  }

  public double get(int i)
  {
    return LslAndroidJNI.vectord_get(swigCPtr, this, i);
  }

  public void set(int i, double val)
  {
    LslAndroidJNI.vectord_set(swigCPtr, this, i, val);
  }
}
