/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.lsl;

public class XmlElement
{
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected XmlElement(long cPtr, boolean cMemoryOwn)
  {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XmlElement obj)
  {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize()
  {
    delete();
  }

  public synchronized void delete()
  {
    if (swigCPtr != 0)
    {
      if (swigCMemOwn)
      {
        swigCMemOwn = false;
        LslAndroidJNI.delete_xml_element(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public XmlElement(SWIGTYPE_p_lsl_xml_ptr obj)
  {
    this(LslAndroidJNI.new_xml_element(SWIGTYPE_p_lsl_xml_ptr.getCPtr(obj)), true);
  }

  public XmlElement first_child()
  {
    return new XmlElement(LslAndroidJNI.xml_element_first_child(swigCPtr, this), true);
  }

  public XmlElement last_child()
  {
    return new XmlElement(LslAndroidJNI.xml_element_last_child(swigCPtr, this), true);
  }

  public XmlElement next_sibling()
  {
    return new XmlElement(LslAndroidJNI.xml_element_next_sibling__SWIG_0(swigCPtr, this), true);
  }

  public XmlElement previous_sibling()
  {
    return new XmlElement(LslAndroidJNI.xml_element_previous_sibling__SWIG_0(swigCPtr, this), true);
  }

  public XmlElement parent()
  {
    return new XmlElement(LslAndroidJNI.xml_element_parent(swigCPtr, this), true);
  }

  public XmlElement child(String name)
  {
    return new XmlElement(LslAndroidJNI.xml_element_child(swigCPtr, this, name), true);
  }

  public XmlElement next_sibling(String name)
  {
    return new XmlElement(LslAndroidJNI.xml_element_next_sibling__SWIG_1(swigCPtr, this, name), true);
  }

  public XmlElement previous_sibling(String name)
  {
    return new XmlElement(LslAndroidJNI.xml_element_previous_sibling__SWIG_1(swigCPtr, this, name), true);
  }

  public boolean empty()
  {
    return LslAndroidJNI.xml_element_empty(swigCPtr, this);
  }

  public boolean is_text()
  {
    return LslAndroidJNI.xml_element_is_text(swigCPtr, this);
  }

  public String name()
  {
    return LslAndroidJNI.xml_element_name(swigCPtr, this);
  }

  public String value()
  {
    return LslAndroidJNI.xml_element_value(swigCPtr, this);
  }

  public String child_value()
  {
    return LslAndroidJNI.xml_element_child_value__SWIG_0(swigCPtr, this);
  }

  public String child_value(String name)
  {
    return LslAndroidJNI.xml_element_child_value__SWIG_1(swigCPtr, this, name);
  }

  public XmlElement append_child_value(String name, String value)
  {
    return new XmlElement(LslAndroidJNI.xml_element_append_child_value(swigCPtr, this, name, value), true);
  }

  public XmlElement prepend_child_value(String name, String value)
  {
    return new XmlElement(LslAndroidJNI.xml_element_prepend_child_value(swigCPtr, this, name, value), true);
  }

  public boolean set_child_value(String name, String value)
  {
    return LslAndroidJNI.xml_element_set_child_value(swigCPtr, this, name, value);
  }

  public boolean set_name(String rhs)
  {
    return LslAndroidJNI.xml_element_set_name(swigCPtr, this, rhs);
  }

  public boolean set_value(String rhs)
  {
    return LslAndroidJNI.xml_element_set_value(swigCPtr, this, rhs);
  }

  public XmlElement append_child(String name)
  {
    return new XmlElement(LslAndroidJNI.xml_element_append_child(swigCPtr, this, name), true);
  }

  public XmlElement prepend_child(String name)
  {
    return new XmlElement(LslAndroidJNI.xml_element_prepend_child(swigCPtr, this, name), true);
  }

  public XmlElement append_copy(XmlElement e)
  {
    return new XmlElement(LslAndroidJNI.xml_element_append_copy(swigCPtr, this, XmlElement.getCPtr(e), e), true);
  }

  public XmlElement prepend_copy(XmlElement e)
  {
    return new XmlElement(LslAndroidJNI.xml_element_prepend_copy(swigCPtr, this, XmlElement.getCPtr(e), e), true);
  }

  public void remove_child(String name)
  {
    LslAndroidJNI.xml_element_remove_child__SWIG_0(swigCPtr, this, name);
  }

  public void remove_child(XmlElement e)
  {
    LslAndroidJNI.xml_element_remove_child__SWIG_1(swigCPtr, this, XmlElement.getCPtr(e), e);
  }
}
